### ISSUE TITLE
Can't see extensions prices

### ISSUE THREAD

**Issue by AmiSimon** [radimitrov/CSharpShellApp#107]
When I try to see the price of the extensions it don't work, it's only showing me "none"

**Comment by radimitrov** [comment]
That suggests failure to connect to Google Play payment services.
Probably a firewall if you're trying this at work.

The only other similar incident I'm aware of is from Russia, where Google has disabled their purchase services. 
Supposedly, things that were already purchased should still work, but I think I read about connection issues a few days ago.
The only alternative right now would be the app's Huawei AppGallery version, if you're from Russia.
Though there is no way to transfer anything between the Google and Huawei stores.
