### ISSUE TITLE
PE image doesn't contain managed metadata

### ISSUE THREAD

**Issue by AmiSimon** [radimitrov/CSharpShellApp#108]
Hello,

I'm trying to run a Xamarin.Forms program but it's always says "Metadata file "assemblies/AndroidHtmlUiLib" could not be opened -- PE image doesn't contain managed metadata"

I don't know what is it, please help me !

**Comment by radimitrov** [comment]
Hi,
Wait a few days for a major update. 
Looks like the old issue with some assemblies failing to decompress.
I haven't seen this problem in development builds for months, so it might be fixed.

**Comment by AmiSimon** [comment]
Thanks a lot !!!
