### ISSUE TITLE
How long until the update?

### ISSUE THREAD

**Issue by TMThong** [radimitrov/CSharpShellApp#110]
I heard you say it will refresh the system. Can you add java ide to that system to build apk in combination with c#?

**Comment by radimitrov** [comment]
Should be under a day for the C# Shell update.
Do you mean support for Java bindings in C# Shell. The Java part isn't the issue, it's the "glue". It would take a lot to even try running the required binding tooling under Android.
Or the Java IDE app I've released? Yes, that can get APKs easily when I get to it within a few months.
