### ISSUE TITLE
Improvement of copy/paste and undo/redo handling

### ISSUE THREAD

**Issue by Alisis33** [radimitrov/CSharpShellApp#112]
The clipboard and undo/redo are some of the most importand operations, and specialy if there is no mouse and keyboard.

I found the copy/paste button very unhandy, it play hide and seak and is often overlaid with other infos and so not accessible.

I think it would be better if copy/paste and undo/redo had a fix location at the top bar. To switch the view can be done better in a menu.
Or 1 symbol for each operation type opens a small pulldown.

And all overlaid infos could be indicated with a smal symbol, and only show there content be clicking on it, instead of overlie code. The display is very small specialy on a phone, where I use the software. Even this symbol could have his place in the top bar.

**Comment by radimitrov** [comment]
The editor is designed is for the "..." copy paste menu to jump around where you type. I've removed that and pinned a different one. It hides when you type text and shows when you click on a character/word.

However, I'm not sure making it part of the toolbar is a good idea. I don't want to remove anything from the toolbar to make space.
But how about like in the picture? Same amount of clicks to open it. Or a slide.
![copy_paste_toolbar_scribble](https://user-images.githubusercontent.com/56889141/163470153-778f4aac-e9b1-465e-b196-eb735f365f0e.jpg)

**Comment by radimitrov** [comment]
Well, now that I have slept my drawer idea seems suboptimal...
I'm putting a copy paste widget in the toolbar.
It is triggered by selection and usually closed manually.
Saves a bit of screen space

**Comment by Alisis33** [comment]
I tink you on the right way.

I would consider to use 1 icon for each operation type in the top bar, and a click opens a small pull down with all the functions. So all actions are 2 clicks away and allways visible with enough click spache.

If you analyse what are the most used actions, i would say first it is copy/paste, then undo/redo, then compile, then reflection/function-parameters, and the swich view like code/console/etc.

Even search/replace is important.

So it makes sense to place the most freqent actions at the most prominent place. For me, copy/paste is way more important then view swich. The hide and seek behavior and the smal size was often annoying for me, I often miss the click, displace the cursor, or could not use the function at all, because of overlay. I had to disable the parameter info.

(To code on a phone with touchscreen is anyway way more harder then on a PC, so easy intuitive handling even more important.

In case you hafe to explain to users often, that the undo function hides behind the plus, it is a hint that it is misplaced, or at least the icon not intuitive enough.)

(Sorry for the late reply)

**Comment by Alisis33** [comment]
(V 2.5.22)
The new copy/past icon mechanism works good now in workflow.

But there is now a new bug.
If you mark something and you past it's OK, it replaces the marked text. but if you insert at cursor position, it deletes 1 character before the cursor.

It seams to mark internally 1 character hefore the insert operation happen.

**Comment by Alisis33** [comment]
Works for me now
