### ISSUE TITLE
Copy/paste not handles escapes correctly

### ISSUE THREAD

**Issue by Alisis33** [radimitrov/CSharpShellApp#114]
If escaped characters like \t or \b are copy and pasted, they turn in to unescaped.

internaly the \ must be in the process protected with \\\\.

**Comment by TMThong** [comment]
I think you should do 1 with a static Property char or string "whatever" and if you want it can be called with $"Van {Class .Static Property} instance"
![Screenshot_2022-04-13-19-49-19-877_com radinc csharpshell](https://user-images.githubusercontent.com/98743684/163183614-8e1fa3fe-d419-48e0-9339-b3573f6e66ee.jpg)
![Screenshot_2022-04-13-19-49-23-174_com radinc csharpshell](https://user-images.githubusercontent.com/98743684/163183624-43437f36-9c9b-4474-9ef8-2dff38a41a9e.jpg)

**Comment by TMThong** [comment]
You can also use string.Format or string.Replace method instead of $"" like I said.

**Comment by radimitrov** [comment]
No, @Alisis33 is correct. This is an editor issue. Once upon a time it was necessary to escape/unescape when doing copy/paste in the editor. I've forgotten to remove that. Fixed it now. Will be in the update after 2.5.18, some time this week.

**Comment by Alisis33** [comment]
Works now, cam be closed
