### ISSUE TITLE
Isues with the search and replace dialog

### ISSUE THREAD

**Issue by Alisis33** [radimitrov/CSharpShellApp#116]
I like the new search/replace design.
But it seams something wrong with the click reaction.
If i try to paste something in the search field, it marks instead a text behind the dialog.

Maybe it could be usefull to place the dialog right above the keyboard, and keep the cursor allways visible. Very smal space for the code, but probably enough to navigate.

But the dialog must be the area of click action, not the text behind.

**Comment by radimitrov** [comment]
That won't work. That is the editor's dialog. It is buggy on mobile. No real way to fix it. I meant it as a temporary solution.
But the design is sound, yes. I've adapted it into a native version that seems to be completely as of today.

**Comment by Alisis33** [comment]
Works now
