### ISSUE TITLE
Ef core nuget bug

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#117]
When I want to install an entity framework core(sqlite and normal also) even if I choose lower then 7.0.0 preview, like 5.0.15 it wants to download 7.0.0 preview
![Screenshot_20220418_145615_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/163811501-914ffcc6-392a-4792-bb40-cc2f01f694e5.jpg)
![Screenshot_20220418_145534_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/163811529-747e1d74-3e8f-483d-8ac5-bf36d4ec6bae.png)

**Comment by radimitrov** [comment]
Good catch. Somehow I missed that in testing. It is fixed for the next release.

**Comment by kovlevi** [comment]
Found another nuget bug, but not only with ef core: I have a nuget in repository sometimes when I try to click it it adds another nuget package to the project. For example want to add Microsoft.entityframeworkcore.sqlite, but instead it adds Microsoft.entityframeworkcore.relational
