### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#119]
![Screenshot_20220421_151539_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/164466121-a786df3f-acf4-47ba-b397-69fded93ada4.jpg)
I don't know what's the problem, but this happens only after adding nuget packages to projects I guess(It is appears a lot of time, don't know the exact reason)

**Comment by radimitrov** [comment]
Very weird, indeed. A compile time error. [Look ](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1.asspan?view=net-6.0) at where "AsSpan()" is implemented, however it says >= 5.0 [here](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/4.1.0).
Compiling the app with System.Collections.Immutable.7.0.0-preview.3.22175.4 fixed it.
