### ISSUE TITLE
Suggestion: Select folder when selecting project files

### ISSUE THREAD

**Issue by giladfrid009** [radimitrov/CSharpShellApp#12]
A nice feature which would make life easier could be adding the option to select whole folder (and sub folders) to be added to the project files.

I guess to avoid problems the app should require the user to pick the main file first and only then permit whole folder selection.

**Comment by radimitrov** [comment]
Yes, it can be useful.
I'll add it as part of the file selection window.

**Comment by wandors** [comment]
Please add support for .resx files

**Comment by radimitrov** [comment]
I'll be adding the select all files in (sub)folder(s) this week. Along with copy and move.

RESX files? I can't. They have Windows.Forms dependencies.
I'm guesing you wanted to use them for assembly resources? That part can be supported.

**Comment by wandors** [comment]
@radimitrov translation into Russian does not work properly installing apk and other menu items
