### ISSUE TITLE
WebClient not found

### ISSUE THREAD

**Issue by jseo-team** [radimitrov/CSharpShellApp#120]
Why c# shell wont let me use System.Net.WebClient or any nuget package likely to replace it ?

**Comment by jseo-team** [comment]
![Screenshot_20220422-003903](https://user-images.githubusercontent.com/70235334/164562911-1d9a6759-0e50-4cd0-8cd9-24eab0841936.png)

**Comment by radimitrov** [comment]
You have forgotten or deleted the "System.Net" using line. And packages need to be manually included to a project after they are downloaded
![webclientss](https://user-images.githubusercontent.com/56889141/164565761-f5467b45-18b9-48d7-bcad-56d56429dbd4.jpg)

**Comment by jseo-team** [comment]
I am sorry but I really think I do have a problem
![Screenshot_20220422-012215](https://user-images.githubusercontent.com/70235334/164566765-745edb2e-3d7c-4597-9ea2-88afddfe5de2.png)

**Comment by jseo-team** [comment]
I think it's all about my android version. I also have a flickering menu and no copy/paste buttons

**Comment by jseo-team** [comment]
Android 8.0.0

**Comment by Mitchbux** [comment]
I confirm the bug 
![Screenshot_20220422_015650_com radinc csharpshell](https://user-images.githubusercontent.com/55109545/164569718-22774939-7a0b-4cb2-b02c-96de85ca854b.jpg)
Was fine before the last update

**Comment by radimitrov** [comment]
The problem isn't Android 8.0 as far as I can tell.
The toolbar in your screenshot is gone. Just visually, it appears. There is nothing in the app code that hides it.
And if an error did occur on startup, then the editor would be gone too.
I think it is an error during the Google Play update. Missing resources? 
Try freeing up some space to be safe and updating again.
I just noticed that "System.Net" namespaces aren't explicitly referenced by default. I'm fixing that now.

https://user-images.githubusercontent.com/56889141/164625931-dda9b7e7-1523-4082-acfe-b25847dcc6d4.mp4

**Comment by Mitchbux** [comment]
Fixed!!
::/ Thank you very much /::
