### ISSUE TITLE
PermissionExeption in new version

### ISSUE THREAD

**Issue by Alisis33** [radimitrov/CSharpShellApp#122]
This is maybe offtopic here, so feel free to delete it.

I got now in the new version a PermissionExeption with the hint to change the AndroidManifest.xml
Usind Battery_Stats and more in the code.

This error did not hapen in the old version. Has someone a tip to fix it? The informations I found don't  work under CsShell.

A working example in CsShell would be usefull.

**Comment by radimitrov** [comment]
Seems I accidentally removed the permission at some point. I'll add it again. What uses it and throws the exception anyway?

**Comment by Alisis33** [comment]
I will test it soon.

Obviously i get even more errors like this if i compile a APK.
I would be very tankful for a example how to implement permissions in to my own code, specialy for CsShell.

Tanks much!

**Comment by Alisis33** [comment]
Battery_Stats permission works now
