### ISSUE TITLE
Entity framework core sqlite nuget not works as Should, I guess

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#124]
I added Microsoft.entityframeworkcore.sqlite to project, but not recognizes it(xamarin forms) 
![Screenshot_20220425_194747_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/165145363-a620b1e7-7256-4362-82e5-a985033c7b85.jpg)
![Screenshot_20220425_194719_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/165145377-ab1c5a24-9e51-44fe-a9f6-fa097ebaaa79.png)

**Comment by radimitrov** [comment]
It's fixed for tomorrow.
