### ISSUE TITLE
Use of entity framework core 5.0.15

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#125]
How can I use entity framework core 5.0.15 in xamarin forms? 
This is the error:
[Error] CS1705: Assembly 'Microsoft.EntityFrameworkCore.Sqlite' with identity 'Microsoft.EntityFrameworkCore.Sqlite, Version=5.0.15.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.EntityFrameworkCore, Version=5.0.15.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.EntityFrameworkCore' with identity 'Microsoft.EntityFrameworkCore, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

But I don't understand where is the reference to entity framework core 2.2.0.0

Added sqlite nuget package:

![Screenshot_20220426_070935_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/165226021-8fb6d191-b8da-495c-bfe7-251fdabbd567.jpg)

**Comment by radimitrov** [comment]
It's the version that comes bundled with the app. It needs to use that. Though it didn't cause any issue when I tested it.
I will see to what version it can be updated without breaking anything.

**Comment by kovlevi** [comment]
Thanks, hope you can add version 5.x.x,but if you can't I will use 2.2.0.0 then

**Comment by radimitrov** [comment]
I just tried to update. It's going to remain version 2.2 for now.
The embedded ASP.NET Core 2.2 can't handle anything else at runtime.

**Comment by kovlevi** [comment]
All right, thanks for the info
