### ISSUE TITLE
XAML Components doesn't auto complete

### ISSUE THREAD

**Issue by AmiSimon** [radimitrov/CSharpShellApp#126]
When in XAML I create a component like a label (for the example, it is named "testLabel"), I doesn't auto complete.
When i write `testL`the auto completion window opens but there is not the `testLabel` wrote in it.
But when I do`testLabel.Text = "ThisIsAText"` the label does show ThisIsAText. Could you fix this ? This would be very useful for my xamarin app 😁

**Comment by radimitrov** [comment]
I'll fix that for the next update.

**Comment by AmiSimon** [comment]
Thank you !!
