### ISSUE TITLE
Ef core nuget bug C# Shell latest version

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#129]
It says I need to use entity framework core  2.2.0 and I use that version, but it says I don't use that. This is since C# SHELL latest update, with existing  xamarin forms project
![Screenshot_20220503_190824_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/166504233-403942eb-0178-43af-be86-9d1f356d2a80.jpg)
![Screenshot_20220503_190814_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/166504251-488b0ace-0a9e-4d3e-8b2c-2ea369d36f92.jpg)

**Comment by kovlevi** [comment]
I fixed it by redownloading C# Shell, and also needed to redownload nuget packages

**Comment by radimitrov** [comment]
Yes, that is one way to fix it. Won't be a problem again in the future
