### ISSUE TITLE
'Allow unsafe code' seems to be ignored

### ISSUE THREAD

**Issue by Dathuss** [radimitrov/CSharpShellApp#132]
Hey. There's an issue when compiling a project with unsafe code. Well, it doesn't compile. I always get the CS0227 error telling me unsafe code can only appear when compiling with /unsafe, however I did tick 'Allow unsafe code' in the project settings, and even after restarting the app, it refuses to compile. I tried to find a workaround but... nope, so guess it's a bug. Please look into this, I like pointer magic. Thanks.

**Comment by radimitrov** [comment]
Indeed. It's fixed for the next update in a day or two.
