### ISSUE TITLE
APK support moved from Google Play

### ISSUE THREAD

**Issue by radimitrov** [radimitrov/CSharpShellApp#143]
In July 2022 Google have enforced a new policy regarding installation of packages and bundling of APKs, which is problematic since the app uses 2 as templates. Scroll to the Request Install Packages Permission section of the [link](https://support.google.com/googleplay/android-developer/answer/11899428). 
Non-compliant apps are deleted from the Play Store.  So APK support was removed from Google Play.

There are 3 options to get (back) APK exporting support.

1. Install the new [custom build](https://drive.google.com/drive/folders/10B01IyEyUZj8PQpG3JDqf4Hc2bcDFB5V?usp=sharing) of the app. No need to uninstall the Google Play version as they have different package names. Due to policies the Google billing services aren't in this version. However this custom version can read purchase states because the Google Play version now saves hashed product ID only versions of them in a remote database.
Note that this database entry is invalidated 48 hours after making a purchase - the self refund window.
The custom version has a button in the premium screen to update/activate purchases.
This custom version also provides a variant of the app that supports full storage access on Android >= 11.

2. Install the Huawei AppGallery version of the app.
However it isn't available in the US. 
Also requires installing a second app store and a second set of (Huawei) services.

3. Don't update to 2.6. Version 2.5.140 is the last one before 2.6.
You would need to uninstall the version from Google Play first. You can get it from [here ](https://apkcombo.com/c-shell-net-ide/com.radinc.csharpshell/download/phone-2.5.140-apk) for example.

There isn't a fourth option however you can use the export assembly (DLL/EXE) functionality and create a launcher shortcut. The assembly will only run inside C# Shell, so it isn't an independent app. More like a shortcut to your compiled projects.

**Comment by Alisis33** [comment]
In case this is possible, add maybe this functions with a plugin externali in to csshell. And publish it here or on a website.

I would greatly miss this function!

**Comment by radimitrov** [comment]
A plugin would just make the total install size considerably bigger. Also use of said plugin could be a very gray area from a Google Play perspective. The current plan for a separate build on the app is better.

**Comment by Alisis33** [comment]
In this case, true. If there is a way to export APKs all is OK.
Only dont let this bigtec monsters take all from as.

**Comment by radimitrov** [comment]
APK stuff is just moving. But yeah... it is going to be really annoying editing the CSharpShell.csproj manually to create a new  compile switch. I'll be making backups after every step because I'm sure I'll break it completely a few times LOL

**Comment by x-DataError-x** [comment]
Man, hang in there, I'm sure you can fix it if you break it 👍 backup the backups lol

**Comment by x-DataError-x** [comment]
Awesome 👍

**Comment by Alisis33** [comment]
Would be the galaxy store from Samsung or  one of the alternative stores like aptoide a solution?
Only keep away from a other monster! Smaler is bether.

I sadly updated without to check the version... (the ttf problem was still not fixed) now I have to find my way back without loosing the purchase...

**Comment by radimitrov** [comment]
Something like Aptoide. Maybe. I need to verify I can upload 2 different versions first.
Purchases should be accessible through the new custom version.  Not making purchases, just reading if you have existing ones. Open the premium screen in the Google Play version and you should see them as an encoded string at the bottom. Same in the custom version.

The TTF problem seems to be also be a Xamarin.Forms issue in general. 
There isn't any reason why it should stop working.

**Comment by Alisis33** [comment]
There are some alternatives out there, beside the monsters...

(TTF off topic here, I write something here #170)

**Comment by romausnul** [comment]
![1674123333524.jpg](https://user-images.githubusercontent.com/119739400/213628843-a921d198-1ada-4544-8719-3dc8af8661cd.jpg)

**Comment by Davovas** [comment]
Hfjf

**Comment by romausnul** [comment]
> Hfjf

![IMG_20230207_205643_420.jpg](https://user-images.githubusercontent.com/119739400/217542717-976cf8e4-aedf-4efb-a6ae-f37a5f338416.jpg)

**Comment by romausnul** [comment]
> Hfjf

![1675537481115.jpg](https://user-images.githubusercontent.com/119739400/217542813-a1e58af1-c221-4793-acd3-97d6c4f16092.jpg)

**Comment by radimitrov** [comment]
Closing this, since APK support is now back as an optional Google Play plugin/app.

**Comment by romausnul** [comment]
![Снимок_экрана_2023-03-26_234959-transformed](https://user-images.githubusercontent.com/119739400/236799732-a0ecfaab-1ef3-4193-acf8-86ebf7ef2149.png)
