### ISSUE TITLE
Custom themes suggestion

### ISSUE THREAD

**Issue by Chazdragons** [radimitrov/CSharpShellApp#15]
I'm not sure how hard or easy this would be to do, but it would be a really good feature if you could select the background color/variable color/string color ect...
 I know that there are themes you can pick and that's great, but it'd really hit the spot if these were things that you could change. 
I'd also like to thank you for this app as it has really made my hobby easier. Im very sorry for wasting your time and I hope to hear back soon.

P.S I'm very sorry this is in the issues section but I just got github to send this to you and am unfamiliar with it.

**Comment by radimitrov** [comment]
The editor is designed to accept themes as a fixed list of ".js" files. But they biscally contain a CSS string.
So maybe. I'll see if the files share the same structure
