### ISSUE TITLE
Videoplayer for xamarin forms

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#154]
What videoplayer can I use in xamarin forms, because Mediaelement is only found in Xamarin.CommunityToolkit(not in xamarin forms 5.0), but I guess it's java Binding issue, which you can't solve I guess?

**Comment by kovlevi** [comment]
It seems that I maybe doing something wrong, but I don't know.

**Comment by radimitrov** [comment]
Yes, they moved MediaElement in one of the Xamarin.Forms minor updates. And the Java binding prevents loading it at runtime via Xamarin.CommunityToolkit.
I could add Xamarin.CommunityToolkit to the app? It isn't big and it does have some interesting stuff like MediaElement and CameraView.

**Comment by kovlevi** [comment]
I would thank you if you would add Xamarin.CommunityToolkit to the app if you really can
