### ISSUE TITLE
Bug with ef core

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#155]
This is the exception:

![Screenshot_20220530_112018_com companyname tartozasok](https://user-images.githubusercontent.com/90194413/170961604-0bbd280f-e867-495d-b23a-bbfdb1c21013.jpg)

![Screenshot_20220530_112056_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/170961674-ca4ebeb9-cb64-4cb5-900d-b69f8349adbd.png)

So it seems SQLITEPCL.Batteries not found, but I need that because of the first exception. I added xamarin forms(latest) from nuget, entity framework core sqlite from References.

Please help!

**Comment by kovlevi** [comment]
Source code:

**Comment by radimitrov** [comment]
Indeed, there seems to be a problem with handling these packages. I'll implement a workaround.

**Comment by kovlevi** [comment]
When will you add this workaround that you mentioned?

**Comment by radimitrov** [comment]
Already done. I might release an update by tomorrow.
