### ISSUE TITLE
Find function not works properly

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#156]
When I want to search for something in my code searching only works for the first found item(with right arrow) , when pressing arrow again it doesn't moving to the next found
position

https://user-images.githubusercontent.com/90194413/171598568-da4e657e-0909-4b02-8b6b-83c315387a54.mp4

**Comment by radimitrov** [comment]
That is to be expected. But it gave an idea for the back find. Looks like it's fixed now.
