### ISSUE TITLE
Ef core overriding savechangesasync bug

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#157]
[Tartozasok.zip](https://github.com/radimitrov/CSharpShellApp/files/8832765/Tartozasok.zip)

As you can see I have this project. In Service/Impl folder there is a Database class where I try to overwrite savechangesasync(entity framework core) to get validationerrors, but I don't think this is called, just saves the data. I tested this in Visual Studio with xamarin forms and it works(throws exception with validationerrors, but not works in C# Shell with xamarin forms). Please help me!

**Comment by radimitrov** [comment]
No idea. I think it's called but might not do anything. This is all I got when entering stuff at random, but I'm not sure which text field maps to what.
![Screenshot_2022-06-03-21-59-21-39_34a6d98a692cc486244154ed8990cd07](https://user-images.githubusercontent.com/56889141/171933998-29400986-3582-4cb7-912f-288799511b94.jpg)
![Screenshot_2022-06-03-21-59-04-14_34a6d98a692cc486244154ed8990cd07](https://user-images.githubusercontent.com/56889141/171934006-dfdacc4b-deb5-4e8d-8454-1af615e5e4cf.jpg)

**Comment by kovlevi** [comment]
But the problem is it doesn't show validationredults when there are any. You can see the code in the Database.cs file when overriding SaveChangesAsync

**Comment by radimitrov** [comment]
Yes, but it seems to work for me. Probably because I've got a clean database. Try deleting yours and then the database should be recreated correctly.
![IMG_20220603_222404](https://user-images.githubusercontent.com/56889141/171940174-7a2ab170-74c4-4735-9e14-1cef03cac277.jpg)
n

**Comment by kovlevi** [comment]
Will try, thanks

**Comment by kovlevi** [comment]
How can I delete my database? (it's in the app data folder and I don't have root)

**Comment by radimitrov** [comment]
Well, you have the path. So just run a File.Delete(dbpath) once
