### ISSUE TITLE
Use of videotrimmer

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#158]
Can I use Xamarin.Forms.VideoTrimmer nuget? Even if I add the nuget it's using didn't found.

Link to nuget: https://www.nuget.org/packages/Xamarin.Forms.VideoTrimmer/

![Screenshot_20220603_162833_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/171874529-174eff48-d779-445e-81eb-0bbe648d8639.jpg)

![Screenshot_20220603_162820_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/171874560-4d2779c7-a9c2-4d5e-990b-8937863a474d.jpg)

![Screenshot_20220603_162810_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/171874591-a51f3b19-ec93-4a44-8e24-3f63a947462e.jpg)

**Comment by radimitrov** [comment]
Yeah, it weirded me out for a moment too. But you can see a "VideoTrimmer" DLL being referenced. And that appears to be the namespace too: "VideoTrimmer", not "Xamarin.Forms.VideoTrimmer". 
![IMG_20220603_222404](https://user-images.githubusercontent.com/56889141/171935647-d2982bad-5fb8-47ad-a0e9-a7f4436ce66f.jpg)

**Comment by kovlevi** [comment]
await VideoTrimmerService.Instance.TrimAsync(1000,5000,Path.Combine(path,"DSfile/szimbolika vicc jószomszédok.mkv"),Path.Combine(path,"test.mkv"));

result in a compiled apk:

![Screenshot_20220603_215809_com companyname myvideotrimmer](https://user-images.githubusercontent.com/90194413/171941444-e50d0350-6d21-4252-9024-7eae8ec291e5.jpg)

**Comment by radimitrov** [comment]
But it works in the C# Shell app? Strange.

**Comment by kovlevi** [comment]
Well, it only works as in the compiled app, just not showing the exception without toast or displayalert

**Comment by radimitrov** [comment]
Hmm, dependencies say Xamarin.Forms >= 4.3. Maybe it isn't compatible with Xamarin.Forms 5.0. I'll take a peak at that library's code

**Comment by radimitrov** [comment]
[Got it](https://github.com/sreerajPR/Xamarin.Forms.VideoTrimmer/blob/master/VideoTrimmer/PlatformImplementations/Android/VideoTrimmingService.cs). It uses [MediaMuxer](https://developer.android.com/reference/android/media/MediaMuxer), which doesn't support ".mkv".

**Comment by kovlevi** [comment]
![Screenshot_20220603_221613_com huawei browser](https://user-images.githubusercontent.com/90194413/171945476-790d6c69-3957-4e25-8f58-4e9049dfe534.png)

It seems the android project also needs this nuget package. Perhaps this is the problem?
