### ISSUE TITLE
Lazyloadingproxies bug

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#168]
In dbcontext(with ef core): 
protected override void OnConfiguring(DbContextOptionsBuilder builder)
    	{
    		string path = Path.Combine(Constants.mainPath,"datas.db3");
    		builder.UseLazyLoadingProxies().UseSqlite($"Filename={path}");
    	}

The builder.UseLazyLoadingProxies(need Microsoft.EntityFrameworkCore.Proxies nuget I downloaded and using it) throws exception, but can't find System.Reflection.Emit 4.0.0(first version I can download is 4.3.0) to download so how can I use it in xamarin forms?

![Screenshot_20220613_120152_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/173330331-8064ee67-4cc9-4a27-b739-05c224510239.jpg)

![Screenshot_20220613_120857_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/173331220-27ba75f5-8b49-489b-9a36-7bfd9eca42d9.jpg)

**Comment by radimitrov** [comment]
A version conflict? It wants something that was removed after version 4.0, I guess. There is no way to fix this type of issue without breaking a lot of stuff in the app.
