### ISSUE TITLE
Error CS1705

### ISSUE THREAD

**Issue by sashamsuper** [radimitrov/CSharpShellApp#169]
The Microsoft.Extensions.Hosting, Version=6.0.0.0 library added via NuGet is not attached to the assembly. Assembly refer to Version=2.2.0.0

I do not understand what the problem is.

Compiling...
Build failed [00:03.205].

[Error] CS1705: Сборка "Microsoft.Extensions.Hosting" с удостоверением "Microsoft.Extensions.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" использует "Microsoft.Extensions.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" с более высокой версией, чем у сборки "Microsoft.Extensions.Hosting.Abstractions" с удостоверением "Microsoft.Extensions.Hosting.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60", на которую делается ссылка.

**Comment by radimitrov** [comment]
The ASP.NET Core 2.2 are forcing the app to rely on that version. If you downgrade to Microsoft.Extensions.Hosting.Abstractions, Version=2.2.0.0, then it should compile. But might not work.

**Comment by sashamsuper** [comment]
if I'm developing a project of Console type, why do I need references to libraries from Asp.NET? Can you remove them from projects that are not of the ASP.NET type and then everything will work?

**Comment by radimitrov** [comment]
No. That is just how a C# compiler can work in Android - 1 process, 1 AppDomain (shared assemblies). Even if it were possible to run a second process of the Mono runtime in a productive way it would increase memory usage beyond the limits of a lot of devices.

**Comment by sashamsuper** [comment]
Why ASP.NET is needed in all types of projects is unclear. If the entire output through it then the question is removed.

**Comment by radimitrov** [comment]
Isn't related to output. 
Basically limitations of the Mono (C# for Android) runtime. Assemblies (your code) can only be loaded dynamically into the same runtime process as the compiler. Anything else is deprecated and would increase RAM at least twice, as well as decrease performance a lot.
