### ISSUE TITLE
App Not Installed error

### ISSUE THREAD

**Issue by xk1430** [radimitrov/CSharpShellApp#18]
i'm getting the app not installed error regardless of my apk project settings, code runs and exports the apk but won't install

**Comment by radimitrov** [comment]
There are several possible reasons. Probably changing signing certificate.
If not then post a screenshot of the main apk settings screen and the signing screen so I can tell you the cause

**Comment by xk1430** [comment]
![Screenshot_20200118_185253_com radinc csharpshell](https://user-images.githubusercontent.com/40346335/72672141-f82a2780-3a23-11ea-9a2d-e09904eedc7a.jpg)
![Screenshot_20200118_185257_com radinc csharpshell](https://user-images.githubusercontent.com/40346335/72672145-fe200880-3a23-11ea-80a6-ea5944f4349c.jpg)
i've tried all the signature algorithms and still wont install

**Comment by radimitrov** [comment]
Yes, the settings should work. They're basically the defaults.
If it is somehow signature related then manually uninstalling the example application should fix.
I'm guessing your device isn't x86 or x86_64? That is the only other reason I can think of.

**Comment by xk1430** [comment]
turns out i didnt have enough memory to complete the installation, i freed some space and everything worked just fine

**Comment by radimitrov** [comment]
Hmm, I'd have thought they'd at least show that. These "application not installed" messages are practically useless.
I'll add it as a note down in the main screen.

**Comment by xk1430** [comment]
thanks for the help
