### ISSUE TITLE
glidex.forms

### ISSUE THREAD

**Issue by TT32-C** [radimitrov/CSharpShellApp#180]
This is not an issue but it's just a question, would you ever mind adding Glidex.Forms to xamarin forms project??

**Comment by pashabhn** [comment]
> This is not an issue but it's just a question, would you ever mind adding.Forms to xamarin form project??
No I didn't to adding.forms to xamarin forms project,  this is the bug

**Comment by TT32-C** [comment]
I have a xamarin forms project and in that project I have ListView that contains all imageFile in my device the problem is it hangs up when ever I switch to that page

**Comment by TT32-C** [comment]
Adding the glidex.forms.Init() in the Main() throws an exception in the console..

**Comment by TT32-C** [comment]
That why Im asking the question, because this nuget package will speed up the rendering for the images..

**Comment by radimitrov** [comment]
No, adding that kind of packages isn't supported. I'm not sure it's entirely compatible either

**Comment by TT32-C** [comment]
Really? That's bad, I thought it's possible.

**Comment by TT32-C** [comment]
If it is not possible, I will just make the UI and code here in csharpshell, cause it is pretty handy and just copy/paste it n VS, I think that will that will solve my problem.
