### ISSUE TITLE
Is there a way to recover savez ?

### ISSUE THREAD

**Issue by Aksword** [radimitrov/CSharpShellApp#186]
Hello, I did a bad manipulation and I lost the code of my file. Is there a way to recover/access the old saves of the files without a cloud systeme?
Thanks

**Comment by radimitrov** [comment]
No, not without cloud. The app just writes changes to the file. The Android file system doesn't have any real type of versioning or recovery of files

**Comment by Alisis33** [comment]
I use packing Software to make a simple ZIP / 7z / rar backup on regular base. Safet me from some very painfull data lust.

Most give you a profile option, to speed up the process.

(Cshell could implement a backupper to zip all files or only code in a project, on button-action or on time base. Usualy not the job of IDEs, but phones and tablets are less powerfull then PCs. Or you can develop one, we are the constructors ;-)
