### ISSUE TITLE
APP REPLACES CONTENT IN .cs PAGES WITH CONTENT OF XAML PAGES FOR NO REASON -or the opposite

### ISSUE THREAD

**Issue by sanmurat131** [radimitrov/CSharpShellApp#189]
I did so many awesome c# projects with this app and now I am a new Xamarin.Forms learner. But for some reason when i try to run my app, it comes with so many snytax errors from a .cs/xaml page. Then everytime i check it out, i see the content of page with errors replaced with another xaml/.cs pages content which i worked on it before. Please help.

EDIT: this problem usually happens when i run the application. I get this issue when I try to run it again 

![PicsArt_08-15-01 23 51](https://user-images.githubusercontent.com/105174798/184557043-2b557c34-121c-4dbd-9ddf-c8c0053e21a3.jpg)
![Screenshot_20220815-011246_C# Shell (C# Offline Compiler)](https://user-images.githubusercontent.com/105174798/184557046-10f1935e-14a1-426c-8398-e36c040bfb6f.jpg)

**Comment by radimitrov** [comment]
Shouldn't be possible. Unless something goes wrong while saving the project state. I'll try a fix for next update.

**Comment by sanmurat131** [comment]
> Shouldn't be possible. Unless something goes wrong while saving the project state. I'll try a fix for next update.

I got the new update and looks like its fixed! The issue didn't happen again. Thanks man, you're the best :)

**Comment by sanmurat131** [comment]
> Shouldn't be possible. Unless something goes wrong while saving the project state. I'll try a fix for next update.

I got the new update and looks like its fixed! The issue didn't happen again. Thanks man, you're the best :)

**Comment by sanmurat131** [comment]
> Shouldn't be possible. Unless something goes wrong while saving the project state. I'll try a fix for next update.

Actually there is one small issue that need to be fixed :'D
In xamarin again, if your code has exceptions, the error screen disappearing so fast -it shouldnt actually- and i cant read exception messages. You can handle it in next update. Big respect. Here is a screen recording.

https://user-images.githubusercontent.com/105174798/185719358-5fb3087e-d4f9-4ed5-8867-b6678658ca81.mp4
