### ISSUE TITLE
System.Media

### ISSUE THREAD

**Issue by Aksword** [radimitrov/CSharpShellApp#193]
Is there a way to play sound files from ressources without System.Media, because I cannot access it.
Thanks !

**Comment by radimitrov** [comment]
You would need to use [system specific APIs](https://developer.android.com/reference/android/media/MediaPlayer).
Something like [this here](https://stackoverflow.com/a/36819228) should work. You would also need to reference Plugin.CurrentActivity to get a context.
var context = CrossCurrentActivity.Current.Activity;
or for an app only shortcut:
Ui.Context / Ui.Activity

**Comment by Aksword** [comment]
Is it possible to do it by creating a raw file ?

**Comment by Aksword** [comment]
> You would need to use [system specific APIs](https://developer.android.com/reference/android/media/MediaPlayer). Something like [this here](https://stackoverflow.com/a/36819228) should work. You would also need to reference Plugin.CurrentActivity to get a context. var context = CrossCurrentActivity.Current.Activity; or for an app only shortcut: Ui.Context / Ui.Activity

Is it possible to do it by creating a raw file ?

**Comment by radimitrov** [comment]
Read WAVE file? Should work with the same code. You would need to use temporary file if it is an asset/resource.
Record WAVE file from microphone? [MediaRecorder ](https://docs.microsoft.com/en-us/dotnet/api/android.media.mediarecorder?view=xamarin-android-sdk-12)should have that.

**Comment by Aksword** [comment]
> You would need to use [system specific APIs](https://developer.android.com/reference/android/media/MediaPlayer). Something like [this here](https://stackoverflow.com/a/36819228) should work. You would also need to reference Plugin.CurrentActivity to get a context. var context = CrossCurrentActivity.Current.Activity; or for an app only shortcut: Ui.Context / Ui.Activity

Sorry, but could you explain it a little more please (I'm a beginner) and I don't really understand how to do it : I dunno where to place the shown code, and I writes errors when I try the code. I know it's more complex than copy-pasting, but I don't really know what to do.

**Comment by radimitrov** [comment]
Start with a Xamarin.Forms project.
Use something like this method at any point after InitializeComponent() or in a button click event.
```csharp
private Android.Media.MediaPlayer player;
private void PlaySoundFile(string filepath)
{
  if (player == null) 
  {
    player = new Android.Media.MediaPlayer();
  }
  player.SetAudioStreamType(Android.Media.Stream.Music);
  player.SetDataSource(Ui.Activity, filepath);
  player.Prepare();
  player.Start();
}

**Comment by Aksword** [comment]
> 

Thanks for the reply ! When I try it, it says that it's impossible to convert a string in Android.Net.Uri on this line : player.SetDataSource(Ui.Activity, filepath);
And also thanks for the advices, I was on a Console project.

**Comment by Aksword** [comment]
> Start with a Xamarin.Forms project. Use something like this method at any point after InitializeComponent() or in a button click event.
> 
> ```cs
> private Android.Media.MediaPlayer player;
> private void PlaySoundFile(string filepath)
> {
>   if (player == null) 
>   {
>     player = new Android.Media.MediaPlayer();
>   }
>   player.SetAudioStreamType(Android.Media.Stream.Music);
>   player.SetDataSource(Ui.Activity, filepath);
>   player.Prepare();
>   player.Start();
> }
> ```

Thanks you (I was on a Console Project) ! But when I write the methods, it says that it cannot convert the string filepath into Android.Net.Uri in this line : 
player.SetDataSource(Ui.Activity, filepath);
And when I do the convertion and call the method in my code, the program doesn't work (it suddenly starts and stops with the notification "program exited").

**Comment by radimitrov** [comment]
Yes, looks like I put the wrong method in the example. Casting directly wont work. Change
```csharp
player.SetDataSource(Ui.Activity, filepath);
```
to
```csharp
player.SetDataSource(filepath);

**Comment by Aksword** [comment]
> Yes, looks like I put the wrong method in the example. Casting directly wont work. Change
> 
> ```cs
> player.SetDataSource(Ui.Activity, filepath);
> ```
> 
> to
> 
> ```cs
> player.SetDataSource(filepath);
> ```

Thanks a lot, it finaly works ! But I have one last issue : when I try to play another sound after the first one, I get "Java.Lang.IllegalStateException: Exception of type 'Java.Lang.IllegalStateException' was thrown.". I tried to fix this by adding a thread.sleep in the method and then a player.stop, but I didn't worked. Do you have any clue please ?

**Comment by Aksword** [comment]
Thanks you, it finaly worked ! I just added a "player = null" at the end of the method to be able to use it several Times.
