### ISSUE TITLE
Two window

### ISSUE THREAD

**Issue by wandors** [radimitrov/CSharpShellApp#20]
Аfter compiling the APK file  on xamarin form and the launcher installed on the phone, two windows appear, how do I hide the second window?

**Comment by wandors** [comment]
`

**Comment by wandors** [comment]
![IMG_20200124_120803 1](https://user-images.githubusercontent.com/19924150/73061958-f89f4400-3ea3-11ea-8ade-42d3c44f9e01.jpg)

**Comment by radimitrov** [comment]
Fixed. I'll probably release an update tomorrow

**Comment by wandors** [comment]
Thank you
