### ISSUE TITLE
Console window setting carrot to top left and scrolling to top

### ISSUE THREAD

**Issue by AppAffection** [radimitrov/CSharpShellApp#203]
Create a new console project and WriteLine a bunch of times until it scrolls off of the buffer window then do a ReadLine a few times. You cannot see the bottom of the screen  where you are typing and if you type fast enough between ReadLines you will see it put the text at position 0,0. Tried on Tab S7 and Note9. Example:

              `public static void Main()
		{
			for (int i = 0; i < 50 ; i++)
			{
				Console.WriteLine("test");
			}
			string res = Console.ReadLine();
			Console.WriteLine("you entered: " + res);
			for (int i = 0; i < 50 ; i++)
			{
				res = Console.ReadLine();
			Console.WriteLine("you entered: " + res);
			}
		}`

**Comment by radimitrov** [comment]
I haven't changed anything in or around the console. I'm not sure why this is happening yet. It appears the console view loses it's scrolling capability for some reason. This is unfortunate.
I'm releasing a workaround for now that makes it work again, but the text still flashes to the top for about 100ms.

**Comment by AppAffection** [comment]
That worked! Thank you so much! Thanks for the very fast response. I hope it is something that is fixable and not too complicated. At least it is usable again!

**Comment by radimitrov** [comment]
Ok, fixed. And so is console text selection. Apparently that was somehow suddenly the cause.

**Comment by AppAffection** [comment]
It works! Thank you!
