### ISSUE TITLE
Assignment 1 example seems off by 1

### ISSUE THREAD

**Issue by dcanelhas** [radimitrov/CSharpShellApp#21]
The comment in assignment 1 is a bit misleading.
Input 51
Output 10 times both buckets

This output would produce 50 liters, (2+3)×10 = 50, missing a half-full scoop of the first bucket or a 1/3 scoop of the second bucket to give the required volume. The example could also be more specific in e.g. prefering as few buckets as possible.

**Comment by radimitrov** [comment]
Ok, this should be more explicit
> 	//Meaning how many times you will use each of them. Including if there is need for a final 'partial' bucket. The buckets are used in parallel.
