### ISSUE TITLE
MS Authenticator

### ISSUE THREAD

**Issue by AppAffection** [radimitrov/CSharpShellApp#210]
I hate to create a bug for this but it is pretty annoying. For some reason when the code pages get focus Microsoft Authenticator keeps prompting to save login credentials. Like when I stop debugging or when I minimize the app and open it again. I am going to file a bug with them too but I imagine something must be set as a password box somewhere in your app and it somehow loses focus? I let it save the credentials on one of the occurances and it saved the username as "Visibility" and the password as "/storage/emulated/0/Android/data/com.radinc.csharpshell/files/CSharpShell/ConsoleApp/Pages". It's no big deal, I will just keep ignoring it but I thought I should at least report the bug as it is pretty annoying constantly being prompted to save some unknown credentials. I'll keep poking around to see if I can find any more details on how to replicate but I thought maybe you might know of some password box that might be losing focus at times? There is no password box being used in the app I am creating. Oh, and this occurs on both Xamarin apps and Console apps. Thanks.

**Comment by radimitrov** [comment]
Microsoft Authenticator? [This app](https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en&gl=US)?
It isn't explicitly integrated, but might pop for initial two factor authentication if you've enabled pCloud file sync for the folder.
No idea why it would put username and password like that, though.

**Comment by radimitrov** [comment]
No, wait. That supports just Google Authenticator as far I can see.

Doesn't seem to do exactly that on my device.
But authentication does fail when two factor auth is enabled. Could be the cause, but either way that needs fixing.

**Comment by AppAffection** [comment]
That is the app yes. I cannot figure out a way to replicate it yet. It is so sparadic. But it only happens when I go to the code page. I am trying to note when it occurs and so far it seems to be when I am on a line with "IsVisible" that may not always be the case though. I will keep noting when it happens bc I know you can't fix it if you cannot replicate it. I don't use any cloud sync. I use the authenticator for 2 factor authentication but I also use it to save all my passwords for different apps (as it does both) but I don't use any password for your app so it is strange that it keeps prompting me to save login credentials and that it saves what I posted above. I wouldn't worry about it until I can get more details for you to replicate, at this point it is just too random.

**Comment by AppAffection** [comment]
Okay I can pretty consistently replicate this now. It still seems to be very specific to a set pattern and I have not narrowed down which steps are truly necessary but here are the basic steps:

1. Create a new project and type a word like "Testing".
2. Double tab the "Testing" word and Ctrl+C to copy it.
3. Open the Find and Replace.
4. Ctrl+V to paste it into the "Search For" box.
5. In the "Replace With" box type "Test"
6. Click All to replace all. (it should replace 1 item)
7. Close the Replace box by hitting the red X.
8. Authenticator should prompt for you to save credentials.
9. If you choose to save it saves the username as "Test" and the password as the file location that your project is in.

Note: To get consistent results make sure there is nothing in the Search For and Replace With boxes before doing the above steps.

![image](https://user-images.githubusercontent.com/88846239/197610662-ffc1a025-cfaa-4380-99cd-1faac2fd57f5.png)

![image](https://user-images.githubusercontent.com/88846239/197610463-15844014-06dc-42f8-a9f6-e46db5858457.png)

![image](https://user-images.githubusercontent.com/88846239/197611599-40a63dd5-5226-4117-98c0-1d149ea9abbc.png)

**Comment by AppAffection** [comment]
Based on the above results it almost seems like the "Replace With" box has IsPassword set to true or something. Although it is saving what is in there as the Username so that doesn't quite seem to be the case, but something along those lines maybe?

**Comment by AppAffection** [comment]
I am on a Galaxy Tab S7 and have a physical keyboard yes. 

If you mean the option that says "Input text composition" I tried it both on and off and can replicate both ways so that does not appear to help. Unless, do I need to restart the app after changing that toggle switch? I did not try restarting after changing the setting.

Okay well I figured there was likely a password box being used somewhere and if that needs to be the case then there is likely no way to resolve it so NBD I'll just ignore it. Unfortunately the Authenticator does not have an option to ignore an app or "don't ask again" which is really a bug on their part so I am going to try to file a feature request with them to allow you to ignore an app or not ask again but it is MS so likely won't be fixed for some time. lol.

I'll leave this open for now in case you still want to take a look and verify that is the issue but you can close it if that is the case. Thank you.

**Comment by radimitrov** [comment]
Ok. Minimizing and going back to the app should recreate the input connection and reset input text composition. But restart the app to be sure.

**Comment by AppAffection** [comment]
Okay that seems to have resolved it. Thanks!
