### ISSUE TITLE
Latest update is awesome. No regrets buying premium pack

### ISSUE THREAD

**Issue by jgranserver** [radimitrov/CSharpShellApp#216]
Exporting assembly is working great and doesn't give me some problem and errors in which it will ask me to include reference assembly in the previous version. Keep up the good job @radimitrov 👍.

I also love the new features added on premium. But there is one thing I want to be in the IDE, the circle button which contain the undo and redo button, can u make it draggable? not just setting it from left to right?

But all other stuffs are fine. Nothing more to ask.

**Comment by jgranserver** [comment]
And also will this app have AssemblyInfo.cs generator?

**Comment by radimitrov** [comment]
I can add it as a template so you can make an AssemblyInfo.cs faster, yes.

Movable floating action button? Should be easy. 
However the available screen space changes every time the phone is rotated. 
And more importantly when the soft keyboard is opened or closed.
So the result might not be what you expect.
