### ISSUE TITLE
Xamarin.Forms.Maps

### ISSUE THREAD

**Issue by firstygoldfish** [radimitrov/CSharpShellApp#219]
Hi Firstly, loving this app and purchased premium to offer a little support.

I have built a couple of prototypes on the road and recently I was trying to use Xamarin.Forms.Maps.
I add the package and can code the app however from the documentation

`Xamarin.FormsMaps.Init(this, bundle);`

Has to be called from the MainActivity. Does this happen automatically when packages are added or is there a way that I can do this?

Thanks

**Comment by firstygoldfish** [comment]
Thanks for the speedy response. I kind of appreciate how it works but didn't know nifty there was anything you could do with the custom builder to be able to add the packages in and the calls as the app is built.

Still a great app for on the go prototyping.

MANY THANKS

**Comment by firstygoldfish** [comment]
Shall injust close this issue as a non starter or will you do that? Again, my thanks

**Comment by radimitrov** [comment]
I'll close it.
Some time after the .NET 6 port I might get around to trying to adapt the entire MSBuild process when there is free time to study it in detail. 
I'm giving the idea a 15% success chance. Because I'm felling optimistic today lol.

**Comment by firstygoldfish** [comment]
Thanks again for the response. Still a great app.
