### ISSUE TITLE
 Change color (style Theam)

### ISSUE THREAD

**Issue by wandors** [radimitrov/CSharpShellApp#22]
Is it possible to change the color that is indicated on the picture, and is it possible to restore the Splash picture when running the program?
![Screenshot_2020-01-29-11-01-38-882_com companyname testers](https://user-images.githubusercontent.com/19924150/73342957-4fcc5c80-4288-11ea-957f-9122ec6749a0.jpg)

**Comment by radimitrov** [comment]
Restore the splash picture? I don't know what that means. 
Status bar Color? You need platform specific code for that. This might do for now if Mono.Android is there entirely:
>  var a = typeof(Ui).GetField("CurrentActivity", BindingFlags.NonPublic | BindingFlags.Static).GetValue(null) as Android.App.Activity; 
 > a.Window.SetStatusBarColor(Android.Graphics.Color.Green);

**Comment by wandors** [comment]
@radimitrov And how is it possible to realize color change through your program?  Show this through a working code example!

**Comment by radimitrov** [comment]
@wandors You can't directly edit the Android theme.  I'm adding that up there as a property. Google Xamarin.Forms resource dictionaries
