### ISSUE TITLE
CS1025, CS1040 with # code at the top

### ISSUE THREAD

**Issue by Alisis33** [radimitrov/CSharpShellApp#223]
In v2.6.59

this errors show up if any code starting with # at the top of the code.

CS1025 with #define
CS1040 with #if

#if error can be solved with a empty line before.

(maybe the compiler can not handle existing/nonexisting UTF8 BOM correctly?)

**Comment by radimitrov** [comment]
No, it's the app's "alias maker". I'll revert the change that caused it.
