### ISSUE TITLE
Some Latest Issues

### ISSUE THREAD

**Issue by BanDroid** [radimitrov/CSharpShellApp#227]
Any news for update v3?

**Comment by radimitrov** [comment]
Yes, but [not good](https://github.com/xamarin/xamarin-android/issues/7624).

**Comment by BanDroid** [comment]
@radimitrov sora-editor is still beta, of course there will be some bugs when you trying to implement lsp for it.

**Comment by radimitrov** [comment]
Uhm, no. These problems are from before I put in sora-editor. I thought the old editor was the source of the issue for a bit.
And I'm not using LSP.

**Comment by BanDroid** [comment]
[This issue](https://github.com/xamarin/xamarin-android/issues/7624) had been closed, the update would be close too isn't?

**Comment by radimitrov** [comment]
Yes, I'll write a short comment on the .NET 7 issue

**Comment by BanDroid** [comment]
Seems the google play will updated first before the apk build support version. What are the big changes in the update?

**Comment by BanDroid** [comment]
The update is cool, editor is much more stable than before, here are some issues i faced with the new migration:

1. I cant choose item in completion.
2. MAUI project cannot use some view (e.g Button).
3. Toolbar and editor collapsed together a little bit.
4. I cant open file treeview more than 2 items collapsed.
5. Some editor options shouldn't be enabled such as delete whole line if empty, soft tab, etc.

Also, if google play version support export apk, then should people still use the apk from gdrive as well?

**Comment by radimitrov** [comment]
1. Yeah, text composition issues. I might have a workaround, but disabling it in the settings is a sure fix. Spacebar cursor movement should still work.
2. Indeed. Didn't have time to test beyond the basics. Seems like a simple fix, though.
3. I know and I have no idea why the toolbar suddenly decided to do that. Lower on the priority list since it is only a visual glitch.
4. Seems to work. A folder won't pop down a tree if it is empty. Or if there are no project files for the project view version.
5. I think empty line deletion could be caused by default keyboard behavior so disabling the solution from 1. should work. I'll open a feature suggestion for optional soft tabs in sora-editor.

Will I stop updating the Google Drive version? Probably not. It is still useful in other ways.

**Comment by BanDroid** [comment]
Here is what i mean by poin 4

[Video Demo](https://drive.google.com/file/d/1IrbN__P7IA4wuELSwv_Uqtw4TjVkVst5/view?usp=drivesdk)

**Comment by radimitrov** [comment]
The video is how it is intendent to work. Collapses all the other trees on the same level to make it more readable.
The other things should be fixed in the next release today. Except the Button problem, that is just a temporary patch.

**Comment by BanDroid** [comment]
> The video is how it is intendent to work. Collapses all the other trees on the same level to make it more readable.
> The other things should be fixed in the next release today. Except the Button problem, that is just a temporary patch.

I figured out, i think the problem was because your C# Shell IDE didn't use material design as the theme, while maui uses it, because i cant run the project directly in IDE, but if i export to apk, it could work just fine

**Comment by radimitrov** [comment]
Yes, exactly. That is now patched up by setting it as the main theme.
The other issues might take more time.

**Comment by BanDroid** [comment]
I'll just closed this issue for now, because only the completion item issue that is left.

**Comment by radimitrov** [comment]
@BanDroid Picking completion by click still doesn't work? That should have been fixed, it works in all devices and emulators. Seems to be a rare issue with some devices, so it may take a very long time to fix, if at all possible.

**Comment by BanDroid** [comment]
> @BanDroid Picking completion by click still doesn't work? That should have been fixed, it works in all devices and emulators. Seems to be a rare issue with some devices, so it may take a very long time to fix, if at all possible.

Yeah it still didn't work in my device, i'll try to get some logs if possible and record some demo.

**Comment by radimitrov** [comment]
@BanDroid I've created the [issue](https://github.com/radimitrov/CSharpShellApp/issues/256). Hopefully I will also be closing it tomorrow.
