### ISSUE TITLE
Monogame projet

### ISSUE THREAD

**Issue by infinity-programeurs** [radimitrov/CSharpShellApp#228]
Svp j'aimerais savoir comment créé un projet en incluant le moteur de jeu monogame avec CSharpShellApp ?

**Comment by radimitrov** [comment]
Not likely to be supported https://github.com/radimitrov/CSharpShellApp/issues/121

**Comment by infinity-programeurs** [comment]
Merci pour la réponse rapide

**Comment by infinity-programeurs** [comment]
Mais es-ce que si une nouvelle version de l'application sorte dont monogame inclus, j'aimerais savoir si ça serait possible d'exporter l'application en apk ?
