### ISSUE TITLE
How'd I use Xamarin?

### ISSUE THREAD

**Issue by BobBlack225** [radimitrov/CSharpShellApp#229]
Hi! I've recently started learning C# and noticed the export apk feature. It seems to work, but it always exports a console/command line type of app. I was wondering how to create a Xamarin form app and export it as an apk. Will I need to manually create the required files and then try? If so, what are the manual files? Thanks in advance!

**Comment by LAXStudios** [comment]
When you create a project, instead of console, click xamarin.forms.

**Comment by radimitrov** [comment]
Yes, creating a new project with the "xamarin forms" type option is the only way to properly do it.
