### ISSUE TITLE
Shell Template

### ISSUE THREAD

**Issue by BanDroid** [radimitrov/CSharpShellApp#236]
The template didn't work, it got error of clr-namespace:CSharp_Shell didn't have local:CatsPage. Also the template when creating new project, could it be following visual studio maui starter project template? It is really hard for beginners to find reference when the template itself was very different from visual studio

**Comment by BanDroid** [comment]
> No, you're doing everything right. This is some kind of MAUI issue. I'm going to dig into the MAUI internals tomorrow to find out more.

So, could you make the project template the same as visual studio? It have toolbar, menu, and basic hello world text, also use resource styling for setup themes

**Comment by radimitrov** [comment]
Not until I work out a workaround for this MAUI bug/limitation that is causing the error.

**Comment by BanDroid** [comment]
> Not until I work out a workaround for this MAUI bug/limitation that is causing the error.

If you already resolved this issue, please notify me, i would close the issue and update immedietly.

**Comment by radimitrov** [comment]
It isn't resolved. I only have 1 more idea that could fix it but it will take time to implement.

**Comment by radimitrov** [comment]
@BanDroid  This should now be fixed in an update that should be available in a few hours.

**Comment by BanDroid** [comment]
> @BanDroid  This should now be fixed in an update that should be available in a few hours. 

Thanks, tested and working!
