### ISSUE TITLE
Each program update overwrites current opened class file.

### ISSUE THREAD

**Issue by BlackHarp** [radimitrov/CSharpShellApp#24]
Hi! The issue happens if the program was not closed before update, that comes from Google.
The last opened file overwrites with current main project file.

**Comment by radimitrov** [comment]
Hi, not updating while the app is open fixes it, yes. It has to be Activity lifecycle related.
The application only saves a "current main project file" path. No previous.
Sub-file of project overwritten by main one? As far as I know that can only happen if the Mono runtime or app is terminated and then the app restarted from a savedBundle. I fixed that last month. It is part of the autosave. It would have to kill the app in an abnormal way to do this.
A simple "don't try to save in background after it was already done" flag should be enough to fix it.
