### ISSUE TITLE
No Microsoft.Maui.Essentials

### ISSUE THREAD

**Issue by jimbob4842** [radimitrov/CSharpShellApp#241]
The type or namespace name 'Essentials' does not exist in the namespace 'Microsoft.Maui' (are you missing an assembly reference?)

Is there any work around?

**Comment by QPLAYid** [comment]
Just add Microsoft

**Comment by radimitrov** [comment]
Yes, just adding a reference to Microsoft.Maui.Essentials.dll will work for a non MAUI project. Should I add this as a "UseMauiEssentials" project option?

**Comment by radimitrov** [comment]
Done, its in the options now.
