### ISSUE TITLE
Exported apk does not display content in console

### ISSUE THREAD

**Issue by WithoutCoffeeBr** [radimitrov/CSharpShellApp#243]
I ended up closing the other topic.
I decide to take a print to demonstrate, I don't know if it's not your test device, but mine is having this problem of not displaying the text.
If I put a readline I can write, but the text is not visible

![Screenshot_20230219_192621](https://user-images.githubusercontent.com/122103334/219978972-81f6d7b9-a883-41a6-82fd-ed06991f4abc.jpg)
![Screenshot_20230219_192630_C# Shell (C# Offline Compiler)](https://user-images.githubusercontent.com/122103334/219978980-997ae4bb-012c-4908-ad10-5d93fe57e55f.jpg)

**Comment by radimitrov** [comment]
Works on my test device but not of my emulator, so progress. The text is black for some reason.

**Comment by WithoutCoffeeBr** [comment]
I tried changing the text color but it had no effect.

**Comment by radimitrov** [comment]
Yes, it is a bug. Something else is forcing the color.

**Comment by WithoutCoffeeBr** [comment]
I changed the theme from my phone to dark mode and popped up the text. The problem should be related to the theme ligth

**Comment by WithoutCoffeeBr** [comment]
![Screenshot_20230220_144716](https://user-images.githubusercontent.com/122103334/220172866-2f2a3aa3-3582-46f8-87bb-d1592b673000.jpg)

**Comment by WithoutCoffeeBr** [comment]
nuget is learning bugs, it is closing and sometimes it doesn't load the repository version.
