### ISSUE TITLE
Appaction bug

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#244]
I made an appaction in a maui app with builder.ConfigureEssentials....AddAppAction....On Appaction...,but when I click it it always shows "application not installed"(alkalmazás nincs telepítve in video, because it's hungarian):

https://user-images.githubusercontent.com/51722783/220287145-648b9f4b-5542-45fb-8969-905c10a26238.mp4

Please help!

**Comment by radimitrov** [comment]
Should work on next update
