### ISSUE TITLE
Update Templates

### ISSUE THREAD

**Issue by BanDroid** [radimitrov/CSharpShellApp#249]
As a beginner in C#, i do really hope the MAUI project template when creating new project, could follow visual studio basic MAUI template that has theme resources, toolbar, and basic native android communication (maybe like snackbar). I have tried implementing this myself, all of this working fine, but my problem is with the theming, i cant update my color from the project itself such as primary color, primary dark, etc. It was still using the theme from C# Shell app.

**Comment by BanDroid** [comment]
I've created something like this

![Screenshot_2023-02-24-07-09-57-179_com.radinc.csharpshell.jpg](https://user-images.githubusercontent.com/68449470/221060046-b1dfbbc3-649e-4c44-b58e-90b88c635b76.jpg)

But i dont think this is the correct way since i'm only looking up for different topic on stackoverflow and doesn't have basic fondation for the project.

**Comment by radimitrov** [comment]
For next update I've implemented most of the template in new projects. However changing theme seems to work only if you make an app for now.

**Comment by BanDroid** [comment]
> For next update I've implemented most of the template in new projects. However changing theme seems to work only if you make an app for now.

Thanks for your hardwork! The new project template is amazing!
