### ISSUE TITLE
resources in this application.

### ISSUE THREAD

**Issue by middle1** [radimitrov/CSharpShellApp#251]
please tell me, do resources work in this application.  If so, how?

**Comment by radimitrov** [comment]
Assembly resources? Open the left (project) panel.

**Comment by middle1** [comment]
> Ресурсы сборки? Откройте левую (проектную) панель.

Well, I understand that, but how to export this resource? I tried using this code, but it didn't work out. There are not even mistakes. Code:
using (Stream resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resName))
using (FileStream fileStream = new FileStream(outputFilePath, FileMode.Create))
{
resource Stream.Copy To(fileStream);
}

**Comment by radimitrov** [comment]
You want to read it manually. What is "resName"?
Resources are stored as paths relative from the project folder but path separators are replaced by "." since "/" or "\" are invalid.
So for example "Images/Animals/cat.jpg" becomes "Images.Animals.cat.jpg"
Either account for that or use the resource helper methods "Ui.GetEmbeddedResource" or "CSharpShellCore.GetEmbeddedResource"

**Comment by middle1** [comment]
resName is "namespace" and the resource file itself.  The file is in the project itself.  not in a folder.  And just namespace and immediately the file name.

**Comment by WithoutCoffeeBr** [comment]
I do resource extraction using ICSharpCode.
![image](https://user-images.githubusercontent.com/122103334/221990550-af65607a-b7b1-4e8d-a924-d3c87c4699dd.png)

**Comment by middle1** [comment]
> I do resource extraction using ICSharpCode. ![image](https://user-images.githubusercontent.com/122103334/221990550-af65607a-b7b1-4e8d-a924-d3c87c4699dd.png)

I don't really understand how this code works.

**Comment by WithoutCoffeeBr** [comment]
ICSharpCode is a library for unzipping zip files. I used it to extract the files of interest that I put in the apk. For me it's something that works, maybe I may not have understood what you're looking for.

**Comment by middle1** [comment]
> ICSharpCode is a library for unzipping zip files. I used it to extract the files of interest that I put in the apk. For me it's something that works, maybe I may not have understood what you're looking for.

Yes, maybe you misunderstood me.  I need to extract the .zip archive to a separate folder from resources.  I just need to move it from resources, not unpack it.

**Comment by radimitrov** [comment]
@middle1 Check what `Assembly.GetExecutingAssembly()` is returning. I suggest storing that in a field.
Then check `assembly.GetManifestResourceNames()`. If it is empty then no assembly resources are added to the project, but are just random files in a directory.
The helper methods I suggested before are also helpful for this.

@WithoutCoffeeBr Also .so native library aren't related to this topic, except that they are stored in a "__AnroidNativeLibraries.zip__" assembly resource by Xamarin tradition.

**Comment by middle1** [comment]
> @middle1 Check what `Assembly.GetExecutingAssembly()` is returning. I suggest storing that in a field. Then check `assembly.GetManifestResourceNames()`. If it is empty then no assembly resources are added to the project, but are just random files in a directory. The helper methods I suggested before are also helpful for this.
> 
> @WithoutCoffeeBr Also .so native library aren't related to this topic, except that they are stored in a "**AnroidNativeLibraries.zip**" assembly resource by Xamarin tradition.

Yes, I checked it.  There is a resource.  And when you export it, an error appears.

**Comment by radimitrov** [comment]
@middle1 Define "export it". And define "error".
As far as I understand you have a resource and use `.GetManifestResourceStream(resName)` which doesn't return null so it returns the resource. If that is so then the undisclosed exception is happening after that point in whatever code you've written. I can't really help you there since I don't know anything about said code or error.

**Comment by WithoutCoffeeBr** [comment]
I am not referring to native libraries in this topic.

**Comment by WithoutCoffeeBr** [comment]
Well now I don't use that as I found out it now has a zip feature so I stopped using ICSharpCode

**Comment by WithoutCoffeeBr** [comment]
I just used this resource Assembly.GetExecutingAssembly() assembly.GetManifestResourceNames(), this topic is being helpful for me.
