### ISSUE TITLE
Code completion not clickable

### ISSUE THREAD

**Issue by radimitrov** [radimitrov/CSharpShellApp#256]
Clicking on a completion item doesn't insert it as expected. This appears to only happen on a few Android 13 devices.
It insert as expected on Android 9,10,12 devices and emulators and on 1 Android 13 Samsung device.
Therefore this issue might take a very long time to fix since I couldn't find a device/emulator that reproduces it.
Update 3.0.28 contains an attempt to fix it.

**Comment by BanDroid** [comment]
Sorry, but my android device is 8.

**Comment by radimitrov** [comment]
Well, just a few Android 13 Samsung users mentioned the problem so it was a logical assumption. I take it the new update had no effect?

**Comment by BanDroid** [comment]
> Well, just a few Android 13 Samsung users mentioned the problem so it was a logical assumption. I take it the new update had no effect?

The new update still not clickable in my device

**Comment by BanDroid** [comment]
Thank you. Your solution to switch from recyclerview to listview actually works

**Comment by radimitrov** [comment]
@BanDroid Yes, but I introduced another problem when scrolling through the completion list. I believe I just fixed it, though.
