### ISSUE TITLE
Selecting text

### ISSUE THREAD

**Issue by iTrooz** [radimitrov/CSharpShellApp#26]
I'm having a really small issue, I think it's my fault, but I can't find out what cause this :
I can't select text in the app. I know there is an "Copy all code" Button, but this is annoying if I need to cut only one fonction.
Thanks for reading !

**Comment by radimitrov** [comment]
DId you try "long touching" text for a little longer? The time might vary to something from 0.5 to 1 seconds depending on device and heavy CPU/memory load.

**Comment by iTrooz** [comment]
I tried touching the text for longer and it worked 😅 thanks, usually I double tap the text to select it, this is why I didn't get it
