### ISSUE TITLE
BlazorWebView maui question

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#263]
Can I make BlazorWebView maui app or can you implement it? (it needs folders like www and need to place my things like index.html there)

Use link: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview?view=net-maui-7.0#add-a-blazorwebview-to-an-existing-app

Visual studio template for this type of project:

[MauiBlazorTemplate.zip](https://github.com/radimitrov/CSharpShellApp/files/10948734/MauiBlazorTemplate.zip)

**Comment by radimitrov** [comment]
I don't think so. The same [problem that prevents ASP.NET Core 7 support](https://github.com/radimitrov/CSharpShellApp/issues/218) will probably be present.
