### ISSUE TITLE
Reference versions problem

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#269]
I can't use a few classes in console app like Stack<>(from System.Collections.Generic) or INotifyPropertyChanged(from System.ComponentModel),because it says this types are forwarded to reference version 
7.0. Please help!

![Screenshot_20230330_233411_com radinc csharpshell](https://user-images.githubusercontent.com/51722783/228970796-aeb5a40b-46a7-49c5-a1dc-5b865d1320f1.jpg)

**Comment by radimitrov** [comment]
Have you added a reference to System.Collections.dll?

**Comment by sedoLevi609** [comment]
@radimitrov Didn'added, I use default, but it's already in the app(, but maybe not the newest version then)
