### ISSUE TITLE
The new update 

### ISSUE THREAD

**Issue by tyronemagwade** [radimitrov/CSharpShellApp#270]
As I updated to the latest update, It is just crushing everytime. I it's not even showing anything without crashing. Can you please the problem as soon as possible

**Comment by radimitrov** [comment]
3.0.50? Can't really do anything since it doesn't crash on any emulator and device I've tried - 7.0,8,12,13.
If clearing data doesn't work then it could be a broken install during update.

**Comment by tyronemagwade** [comment]
![Screenshot_20230401-125627](https://user-images.githubusercontent.com/76815557/229284816-bb53644e-0da1-49d6-8bdf-5df707c572e8.jpg)
![Screenshot_20230401-125623](https://user-images.githubusercontent.com/76815557/229284857-15fbf518-ffaa-455d-8bf4-2620faf67ca8.jpg)
![Screenshot_20230401-125534](https://user-images.githubusercontent.com/76815557/229284871-ad6d69ec-21cb-42b6-9a72-e10404d11a50.jpg)

**Comment by radimitrov** [comment]
Seems like the file for showing privacy policy without internet is missing. A workaround for first start would be if you restart the app after enabling internet access.

**Comment by tyronemagwade** [comment]
Thank you very much, your solution worked

**Comment by sedoLevi609** [comment]
@radimitrov The newest update broke the app, so I can't edit anything, don't even load:

![Screenshot_20230407_080203_com radinc csharpshell](https://user-images.githubusercontent.com/51722783/230551327-84564999-8a49-45a1-bb93-1665a581d9b6.jpg)

Please help!

**Comment by radimitrov** [comment]
@sedoLevi609 This seems to have escaped from all tests however it should be fixed now. I'm uploading an update, though it will be a few hours until Google Play release it.

**Comment by sedoLevi609** [comment]
Yeah, the new update fixed this, thanks
