### ISSUE TITLE
Stuck on 'Downloading...'

### ISSUE THREAD

**Issue by KUNGERMOoN** [radimitrov/CSharpShellApp#276]
The IDE got stuck on 'Downloading...' when I tried to copy/download folder maui-samples-main (from https://github.com/dotnet/maui-samples) from Documents folder on my phone to local storage using file manager

**Comment by radimitrov** [comment]
@KUNGERMOoN  The file manager itself seems to be working as expected. 
However it appears [maui-samples](https://github.com/dotnet/maui-samples) contains several thousand files. And Android's Storage Access Framework is very slow when it comes to a large amount of files. It might need at least several minutes to copy.
