### ISSUE TITLE
All files deleted

### ISSUE THREAD

**Issue by iTrooz** [radimitrov/CSharpShellApp#28]
Hello ! My issue is that this has been two times that all my files ( in differents projets ) deletes themselves. The code, the xaml files and even the assets ( images files ) are deleted. The subfolders remains, so I still have the assets folder for example, but the files in it are deleted.

I have no idea of when or why this happens exactly

**Comment by radimitrov** [comment]
That can't be possible. There is no automatic "File.Delete" call anywhere in this app.
The only one is in the drop down menu, which is only click triggred and needs a a confirmation.
There are also no writing/deleting calls for assets, just reading. 

However you can delete anything from the file manager.

**Comment by iTrooz** [comment]
I will try to work out an external cause of this, thanks ! ( And sorry, this is the second issue from me that is not.. that interesting )

**Comment by radimitrov** [comment]
Hi again. Have you managed to locate the source of the issue? I'm actually curious how that can happen.
BTW you did mean actually deleted files, right? And not just emptied ones?
Even then it still can't be an app issue since it simply refuses to save an empty or null string to file.

**Comment by iTrooz** [comment]
Hello ! So.. I have found the answer, and for some obscure reason, my Code folder was registered as a "garbage folder", and the storage cleaner used to delete every file in this folder periodically ( but never any folder, just the files )

I'm sorry for this issue

**Comment by radimitrov** [comment]
Yes, that makes weird sense. Not sure why it decided to leave the empty husks of sub-folders. I guess the file manager wanted to leave proof of its work 😁
