### ISSUE TITLE
Android.OS

### ISSUE THREAD

**Issue by tosapola** [radimitrov/CSharpShellApp#29]
Hi,

Can I use Android.OS?

Thanks

**Comment by radimitrov** [comment]
Mostly, yes. Reference Mono.Android.dll

**Comment by tosapola** [comment]
> Mostly, yes. Reference Mono.Android.dll

To be more specific, I'm having problem with PowerManager.newWakeLock(). It crashes when run on an complied APK. Any way to use wake lock?

**Comment by radimitrov** [comment]
That is different. Xamarin.Android support is limited to "C# tools only" in this app.
Exporting with Mono.Android to APK doesn't work at all. 
It causes some obscure errors I haven't found a sensible solution for. 

Hence neither of the 2 templates supports it. 
If this does get support eventually it will probably be toggleable in the project configuration
