### ISSUE TITLE
Permission for file access not work anymore in Android 13

### ISSUE THREAD

**Issue by Alisis33** [radimitrov/CSharpShellApp#292]
Permiss now changed in Android 13.
READ_EXTERNAL_STORAGE
WRITE_EXTERNAL_STORAGE
not work anymore..... (this damn hi-tech idiots, how much time we have to waste to clean fix and workaround there nonsense.........)

The problem, I deinstalled and reinstalled the app, an now I have no access anymore to txt and ini etc files in the document folder and folders like /a/b/data/.
In the android options there is no permission anymore for all files, only for media.
The permissions worked until the deinstallation, without deinstallation I would not detect the issue they implemented in V13.

And I don't find in cshell the permissions now needed in Android 13 to access all data anywhere.
The internet is full of buggreports, but i don't find a fix working under cshell.

Pleas some help, the app is in heavy use.
Tanks much.

**Comment by radimitrov** [comment]
True. Now practically only file managers are allowed proper file access with a MANAGE_EXTERNAL_STORAGE permission.
And requesting that permission for a compiler app that technically doesn't require it to function is pretty much a red flag from Google's point of view. Even if they initially grant it they can go back on that or worse at any time for any conceived reason.

The deinstallation and reinstallation of an app basically undoes "preserveLegacyStorage=true" when from an older to a newer Android version.

The app's file manager supports bringing files "in and out" of the app files directory, but that is still limited by Scoped Storage.
Some file managers allow access to that directory. So you just need to move files there:
/storage/emulated/0/com.radinc.csharpshell/files

![x-plore_apps_external_files](https://github.com/radimitrov/CSharpShellApp/assets/56889141/d4f568e4-8a57-4a98-b6a8-131d3c8d59a9)

**Comment by Alisis33** [comment]
$#&###*+ $$$$$$
EVERY SINGLE TIME if I update there $#&#$# I am scared what the hell they Ff$&$&$ next.
If somebody know a better OS, I cone switch and go away from there tyrannycal &#&$666$#.
How much more we need to understand they are totally  evil, and soon we have no access anymore to owed own data, and they can spy and destroy all in there skynet clowd.

If there is a way to downgrade the OS, or get the access permission to the document directory, or hack it, pleas let me know.
There must be a way.

And fill there forums and support with complaints...!!!

...sorrry... but...

Tanks much radimitrov.

**Comment by Alisis33** [comment]
Ps
I not want move the files in a app directory like /storage/emulated/0/com.radinc.csharpshell/files, because then I have no access animore with me favorite file manager.
IT IS ME PHONE AND ME DATA....

**Comment by radimitrov** [comment]
@Alisis33 They should only be for media (jpg, mp4...), though I'm not sure how aggressively that is enforced. 
Media directories can only be accessed by Android API's, and not regular file access (System.IO.File). Such access is necessary for any compiler, unless it enforces total source control over all package dependencies (impossible for user packages) and limits user IO code to specified APIs. In other words it is a very bad idea creating much worse problems.

I only use X-Plore and on occasion File Manager Plus, however access to external files directory of apps seems to be the norm among modern file managers as I remember testing a few more for this. I really can't help in any way if your file manager doesn't support it

**Comment by Alisis33** [comment]
@radimitrov 
I found a solution, and a other day wasted for big-tech nonsense...
In the android options I found a option to allow a app access to ALL data. The option is not in the regular app options, but in the security. 
In German: "Sicherheit und Datenschutz > Datenschutz  > Berechtigungsverwaltung > Dateien und Medien > weitere Apps...

I don't know if a reinstallation of cshell remove the permission. I don't want try it out. But it could cause problems for your users. Be prepared for questions if the users could not compile animore in cshell. And it is confusing if you can not activate the permission in the app option section.

Cshell maybe needs a update for the permissions changes in v13. And i would implement a information how to activate the rights for chshell in case you detect no file access rights. To waste time for such fixes is frustrating.

Frustrating is too that a compiled app whitout a permission check simply crashes, and again a time waster for programmers to find the reason, because it will work on some devices, <v13, and others not.

(To put the files in the app directory would cause that they will be deleted in case of a deinstallation, this should never happen! And the documents directory is the place this type of files should be. But tanks anyway.)

Tanks much for the patience and you replies.

**Comment by radimitrov** [comment]
You're talking about [MANAGE_EXTERNAL_STORAGE](https://support.google.com/googleplay/android-developer/answer/10467955) permission, I've already mentioned here why I can't risk uploading that to Google Play - policy nonsense that you can read for yourself if you want. 

There was a separate build of the app that allowed for that permission, not uploaded to Google Play. However in the recent months Google introduced too much other obstacles for it to function as expected. I'm not to keen on devoting time to updating it in that state.

**Comment by Alisis33** [comment]
@radimitrov i not use the big-tech version, but this you upload to bypasse there suppresions.
Not only MANAGE_EXTERNAL_STORAGE, they changed more I think. But if they keep changing, its better to wait to avoid more confusion. For now me app works. I only expected more trouble for cshell with v13, and more buggreports...
Its goog not you which screwed it.

(
I think big-tech want to make android now to a jail too. And they will, if users not push back. 
I use cry in my app and have no motivation to uplade it to goog.
Everybody complaints about Maui, I have no motivation to learn it now...
But I stop here.
)
