### ISSUE TITLE
Type local:FloatToIntConverter not found in xmlns clr-namespace:XamlSamples

### ISSUE THREAD

**Issue by KUNGERMOoN** [radimitrov/CSharpShellApp#295]
When I try to compile [this project](https://e.pcloud.link/publink/show?code=kZ7WiuZcNkUnHJ3gNF61CettQuk4StEYNwX) on Windows in Visual Studio it runs without any problems, but when I try to compile it using this app, after compiling I get a runtime error: "Position 12:10. Type local:FloatToIntConverter not found in xmlns clr-namespace:XamlSamples"

(Note that to compile attached code on android (in this app), you'll need to create a new project and copy all .cs and .xaml files rather than copying entire project)

**Comment by radimitrov** [comment]
@KUNGERMOoN An issue with the XAML compiler. This appears to be caused by unimplemented types that are replaced by stubs with null returning methods. In this case `Microsoft.Maui.Controls.Xaml.Internals.SimpleValueTargetProvider` from Microsoft.Maui.Controls.Xaml.dll. I haven't yet managed to trick Visual Studio into including the assembly build with the full types.

**Comment by KUNGERMOoN** [comment]
Thanks for response,
I can't wait to learn MAUI, but not being able to reference code in class outside x: namespace was a problem stopping me from doing so (for now I'll just code the UI in C#)

> I haven't yet managed to trick Visual Studio into including the assembly build with the full types.

You meant the C# Shell app?
(or am I misunderstanding something?)

**Comment by radimitrov** [comment]
Visual Studio, yes. It is what is used to compile C# Shell and it is what in this context provides all the framework assemblies.

**Comment by radimitrov** [comment]
@KUNGERMOoN It's fixed. That was easier than expected. There should be an update by tomorrow.

**Comment by KUNGERMOoN** [comment]
@radimitrov I can confirm this bug no longer occurs
