### ISSUE TITLE
XML formatter replaces new line with &#xA;&#x9;&#x9;&#x9;&#x9;

### ISSUE THREAD

**Issue by KUNGERMOoN** [radimitrov/CSharpShellApp#296]
# To reproduce:
- Download [this file](https://e.pcloud.link/publink/show?code=XZ7tXfZ6ArpMGmcA0bFJkAKRKcPGur2eoJ7) and open it in C# Shell app
- Use "Format code" option
- Lines 37 - 40 will be merged into one line, separated by ```&#xA;&#x9;&#x9;&#x9;&#x9  ```, similarly lines 42 - 45 and 47 - 50

# Other issues related to XML formatter
- Formatter will put all xmlns definitions on the same line
- Formatter uses 2-space indentation rather than 4-space or tab, which is (at least in my opinion) inconsistent with the C# code formatter indentation

**Comment by radimitrov** [comment]
The formatter should now behave as expected when it comes to whitespace. The condensed definitions might also be fixed, if not I will deal with it some time next week since it isn't a breaking bug.
