### ISSUE TITLE
Restore editor font? 

### ISSUE THREAD

**Issue by lcocea** [radimitrov/CSharpShellApp#311]
The editor font is not monospace after running my app from the IDE. The only way to restore the original editor font seems to be restarting the IDE. What better options are available?

**Comment by radimitrov** [comment]
@lcocea This doesn't appear to occur and I don't remember it in any test or issue report in the past few months. Can't reproduce the issue or guess as to cause without information like OS and app version and/or a video of what is actually happening.

**Comment by lcocea** [comment]
It turns out it the issue is apparent only in split screen mode, see video attached: Xaml file uses monospace font at first as expected, then app runs (two buttons are shown), then I press Back to quit and return to the Editor wher the Xaml file now uses a non-monospace font (also, the tab character size is now 2 spaces instead of 4). Samsung Galaxy Tab Active3, Android 12, C# Shell 3.11.1
 [https://github.com/radimitrov/CSharpShellApp/assets/1596128/7079fdce-0c0d-4a61-88fc-8634948d3bf9](screen recording)

**Comment by radimitrov** [comment]
Ok, it is fixed for next update.

**Comment by lcocea** [comment]
> Ok, it is fixed for next update.

Thank you. When is this scheduled for release on Play Store?

**Comment by radimitrov** [comment]
@lcocea Less than a day

**Comment by lcocea** [comment]
> @lcocea Less than a day

Nice, it looks good.
