### ISSUE TITLE
How Can I run a downloaded project?

### ISSUE THREAD

**Issue by GatoBinario** [radimitrov/CSharpShellApp#32]
I have downloaded a project and I don't know how to run It

**Comment by wandors** [comment]
Did you upload the project?

**Comment by GatoBinario** [comment]
I don't know how

**Comment by radimitrov** [comment]
Not everything can be imported. 
If it is a Xamarin.Forms project, then there is an example for how to import that.
If it is a Console project then usually just the "add all files in (sub)folder(s) button/step" is needed.
