### ISSUE TITLE
const variable declaration not constant

### ISSUE THREAD

**Issue by Forscythe** [radimitrov/CSharpShellApp#33]
I'm learning C#, and this app does not keep variables declared as const as constant. I can declare the same variable as something different later in the program.

Example
		const double PI = 3.14159265359;
		const int days = 365;
		
		static void Main(string[] args)           
		{
			int days = 39393;
			Console.WriteLine(days);
			double PI = 23.01;
			Console.WriteLine(PI);
}

**Comment by wandors** [comment]
You just overload Pi from a static variable into a non-static variable

**Comment by radimitrov** [comment]
Yes, overloaded it. Scoping goes from the inside out. So first the method and then the class.
And your method and class both have a declared PI field/variable. Also Math.PI.
