### ISSUE TITLE
Can't load local files

### ISSUE THREAD

**Issue by equin0X35** [radimitrov/CSharpShellApp#330]
im just coding around but suddenly i got hit by this issue. setting the webview's source property to local file in resources folder for example "index.html" it this:

Webpage not available
The webpage at file:///android_asset/index.html could not be loaded because:

net::ERR_FILE_NOT_FOUND

configuring the .csproj file, embedding the resource like this `<EmbeddedResource include="Resources/Raw/index.html"/>` and doesn't do anything. I also try setting the source to the actual path of the file but this error `net::ERR_ACCESS_DENIED`. so i then search and found `<MauiAsset Include="Resource/Raw/filename"/>` but same.

**Comment by radimitrov** [comment]
@equin0X35  Only asset would work. However a file only becomes internally recognized from Android as an asset if it is inside the APK package. Meaning you will need to use Export APK every time. There is a helper method for assets (UI.GetAsset) Moving it to move it to "%ProjectDir%/Assets" will enable its resolution and I'm going to modify that so apply for manually added items. However that method can't be used by the OS so it may not be applicable to your use case.

**Comment by equin0X35** [comment]
😩i see, to make my thing go, i need export as it apk first. waiting the next update 👍

**Comment by radimitrov** [comment]
@equin0X35 You could implement it kind of like this using Microsoft.Maui.Essentials to check what the current Android app is:
``` csharp
string basePath;
if (Microsoft.Maui.ApplicationModel.AppInfo.PackageName.EndsWith("csharpshell"))
{
    basePath = $"file:///{Directory.GetCurrentDirectory()}/Assets/";
}
else
{
     basePath = $"file:///android_asset/";
}
var indexHtmlPath = basePath + "index.html";
....
```

**Comment by equin0X35** [comment]
Yeah, this work as expected, but:
Webpage not available
The webpage at file:///storage/emulated/0/Web_sample/Web_sample/Assets/index.html could not be loaded because:

net::ERR_ACCESS_DENIED

**Comment by radimitrov** [comment]
@equin0X35 Check WebView.Settings. There are a few related to file and url access

**Comment by equin0X35** [comment]
I see, i have just try this way and it work😅
```cs
Uri uri = new Uri("http://localhost:26543/storage/emulated/0/Web_sample/Web_sample/Assets/index.html");
			
CookieContainer cookies = new();
Cookie cookie = new Cookie{
        Name = "LocalCookie",
	Value = "UserCookie",
	Domain = uri.Host
}; 

cookies.Add(cookie);
web.Cookies = cookies;
web.Source = new UrlWebViewSource { Url = uri.ToString() };
```

**Comment by PeterKaa1** [comment]
@radimitrov 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.StreamReader..ctor(Stream stream)
   at Local_Notes.MainPage.GetHtmlFromResource(String resourcePath)
   at Local_Notes.MainPage..ctor()
   at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.ShellContent.<>c__DisplayClass19_0.<Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent>b__0()
   at Microsoft.Maui.Controls.ElementTemplate.CreateContent()
   at Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent(DataTemplate self, Object item, BindableObject container)
   at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2)

**Comment by PeterKaa1** [comment]
> @radimitrov
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null. (Parameter 'stream') at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen) at System.IO.StreamReader..ctor(Stream stream, Boolean detectEncodingFromByteOrderMarks) at System.IO.StreamReader..ctor(Stream stream) at Local_Notes.MainPage.GetHtmlFromResource(String resourcePath) at Local_Notes.MainPage..ctor() at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr) --- End of inner exception stack trace --- at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions) at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions) at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions) at System.Activator.CreateInstance(Type type, Boolean nonPublic) at System.Activator.CreateInstance(Type type) at Microsoft.Maui.Controls.ShellContent.<>c__DisplayClass19_0.<Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent>b__0() at Microsoft.Maui.Controls.ElementTemplate.CreateContent() at Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent(DataTemplate self, Object item, BindableObject container) at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent() at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2)

Also trying to acces from Resources/Raw

**Comment by equin0X35** [comment]
> I see, i have just try this way and it work😅
> 
> ```cs
> Uri uri = new Uri("http://localhost:26543/storage/emulated/0/Web_sample/Web_sample/Assets/index.html");
> 			
> CookieContainer cookies = new();
> Cookie cookie = new Cookie{
>         Name = "LocalCookie",
> 	Value = "UserCookie",
> 	Domain = uri.Host
> }; 
> 
> cookies.Add(cookie);
> web.Cookies = cookies;
> web.Source = new UrlWebViewSource { Url = uri.ToString() };
> ```

Maybe best thing do is to add file assest folder and export is as apk for now...

**Comment by PeterKaa1** [comment]
> > I see, i have just try this way and it work😅
> > ```cs
> > Uri uri = new Uri("http://localhost:26543/storage/emulated/0/Web_sample/Web_sample/Assets/index.html");
> > 			
> > CookieContainer cookies = new();
> > Cookie cookie = new Cookie{
> >         Name = "LocalCookie",
> > 	Value = "UserCookie",
> > 	Domain = uri.Host
> > }; 
> > 
> > cookies.Add(cookie);
> > web.Cookies = cookies;
> > web.Source = new UrlWebViewSource { Url = uri.ToString() };
> > ```
> 
> Maybe best thing do is to add file assest folder and export is as apk for now...

So what do i do, i want the html to be loaded from apk Resources / Raw

**Comment by radimitrov** [comment]
Not sure without seeing more of the code. There is no reason this shouldn't be working if it is acknowledged how assets work and paths are correct. Though to clarify, assembly embedded resources wouldn't work here unless you just have "index.html" and if you're getting the resource manually you need to use the full exact name otherwise CSHarpShellCore.Utils/UI.GetEmbeddedResource()

**Comment by PeterKaa1** [comment]
> Not sure without seeing more of the code. There is no reason this shouldn't be working if it is acknowledged how assets work and paths are correct. Though to clarify, assembly embedded resources wouldn't work here unless you just have "index.html" and if you're getting the resource manually you need to use the full exact name otherwise CSHarpShellCore.Utils/UI.GetEmbeddedResource()

What i just want is the app to have an webview which loads html from Resources/Raw

**Comment by equin0X35** [comment]
huhu try this, it works me on😂:

```cs
string curr_dir = $"file:///{Directory.GetCurrentDirectory()}/";
string resRaw = curr_dir + "Resources/Raw/";
			
HandlerChanged += delegate 
{
        using var nativeWeb = web.Handler.PlatformView as NativeWebView;
			
        nativeWeb.Settings.AllowFileAccess = true;
	nativeWeb.LoadUrl(resRaw + "index.html");
};
```

**Comment by equin0X35** [comment]
> huhu try this, it works me on😂: Where `NativeWebView` is type Android webview, this good when just to load html file to webview. see also this [https://stackoverflow.com/questions/75664856/maui-android-webview-can-not-show-local-web-page](url)
> 
> ```cs
> string curr_dir = $"file:///{Directory.GetCurrentDirectory()}/";
> string resRaw = curr_dir + "Resources/Raw/";
> 			
> HandlerChanged += delegate 
> {
>     using var nativeWeb = web.Handler.PlatformView as NativeWebView;
> 			
>     nativeWeb.Settings.AllowFileAccess = true;
>     nativeWeb.LoadUrl(resRaw + "index.html");
> };
> ```

I think this solve the issue for now, i have try before but is not in the `OnHandlerChanged` ethod or in the `HandlerChanged` event instead its in the page constructor.
