### ISSUE TITLE
Package SqlLite doesnt work.

### ISSUE THREAD

**Issue by TimeLord2010** [radimitrov/CSharpShellApp#34]
Nuget package Sqlite cant be imported bia Susyem.Data.Sqllite.

**Comment by radimitrov** [comment]
You have downloaded the package, but it sounds like you didn't include it in the project

**Comment by TimeLord2010** [comment]
I did include it. It even says: SQLite added to project

**Comment by radimitrov** [comment]
Doubtfull, upload a screenshot of the NuGet and Loaded assemblies screens. It should be in both places.
I downloaded "Microsoft.Data.Sqlite" and the using and dll was there. If I remember corrctly that package works for Android. Are trying to use a different package?

**Comment by TimeLord2010** [comment]
Microsoft.Data.Sqlite worked just fine. Thanks
