### ISSUE TITLE
Not Being Able to Use SD-Card

### ISSUE THREAD

**Issue by ChipLag** [radimitrov/CSharpShellApp#344]
why...

**Comment by radimitrov** [comment]
![Screenshot_2023-11-20-22-46-57-44_34a6d98a692cc486244154ed8990cd07.jpg](https://github.com/radimitrov/CSharpShellApp/assets/56889141/3b2652d4-9853-4ccc-88ee-e9224c6171cc)

**Comment by ChipLag** [comment]
?

**Comment by equin0X35** [comment]
I w
