### ISSUE TITLE
Nuget Crashing on browse.

### ISSUE THREAD

**Issue by Monydragon** [radimitrov/CSharpShellApp#352]

**Comment by radimitrov** [comment]
Is this with the latest app version?

**Comment by KUNGERMOoN** [comment]
This might refer to #297

**Comment by radimitrov** [comment]
Yes, it is related to #297 or #297 is just a symptom. This crashes so rarely and with so little useful information that any fix is a guessing game. Right now it looks like browsing isn't working at all, though I suspect a server/API issue since it did yesterday.
