### ISSUE TITLE
Unable to configure the editor font (also it isn't monospace)

### ISSUE THREAD

**Issue by erichiller** [radimitrov/CSharpShellApp#356]
My goal is to have a monospace font for the code editor. Supposedly it is _RobotoMono-Regular.ttf_:

![editor_settings](https://github.com/radimitrov/CSharpShellApp/assets/5379325/23684b38-fdb0-4007-a83c-68c32e155a3f)

But the editor looks like:

![example](https://github.com/radimitrov/CSharpShellApp/assets/5379325/88235167-6f7e-44c7-9b08-a4e5b9d82c59)

I tried clicking the font name, thinking maybe I could add a ttf file, but it is only for text mate themes.

Android 13, app updated to latest in Google Play

**Comment by radimitrov** [comment]
It looks like the primary editor is ignoring the font being set from the preview and resetting to system default. It should be applied on next app start, though.
And the system picker isn't allowing to pick .ttf in Android 12.

Should be an easy fix and update in about a week.
