### ISSUE TITLE
Not showed preview of editor theme

### ISSUE THREAD

**Issue by SKyRo1** [radimitrov/CSharpShellApp#36]
![Screenshot_2020-04-08-01-16-50-974_com radinc csharpshell](https://user-images.githubusercontent.com/13529486/78728090-b92ab480-7936-11ea-900c-6fa46f04b3e6.png)

A trifle of course :)

**Comment by radimitrov** [comment]
Yes, the editor there started wanting to only have a height of 1.
That is fixed for whenver I manage to finish with the new update .
