### ISSUE TITLE
Geolocation support question

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#367]
@radimitrov can I use geolocation(https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/geolocation?view=net-maui-8.0&tabs=android)   with your app(net maui android),it needs these: [assembly: UsesFeature("android.hardware.location", Required = false)]
[assembly: UsesFeature("android.hardware.location.gps", Required = false)]
[assembly: UsesFeature("android.hardware.location.network", Required = false)], but where can I add these in your C# Shell app if it's possible?

**Comment by radimitrov** [comment]
Right now you can't add "<uses-feature .../>" tags. This should be easy to implement. However it might work without these tags. Try with just the permissions. 

And you need to use the Export APK option. I have been thinking about adding a quick deploy option for such cases. Though I'm not sure where it goes on the priority list implementation wise. Soon only if I can figure out the deploy mechanism logic and it isn't too tricky

**Comment by sedoLevi609** [comment]
Yeah, it really works. Thanks

**Comment by radimitrov** [comment]
@sedoLevi609 I also implemented the quick deploy feature successfully. Requires updating both the IDE and plugin and then installing a new Export APK to be quick deployable. Going to finish testing and probably release in a day or two if ok
