### ISSUE TITLE
Ef core(tried with 7 and 8 also) net maui bug with your app

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#368]
I tried using ef core(7 and 8 also) in net maui with your app(inside solution)(installed microsoft.entitytframeworkcore.sqlite nuget package). Something is wrong with the dependencies I think. Looks these exception(when exported APK):
![Screenshot_2024-03-06-13-26-29-363_com companyname timetable](https://github.com/radimitrov/CSharpShellApp/assets/51722783/d62ff42c-44c2-4de0-8e92-6570093d4e6d)

![Screenshot_2024-03-06-13-26-37-385_com companyname timetable](https://github.com/radimitrov/CSharpShellApp/assets/51722783/c5ae2420-1da0-438e-8126-eefae5a4b922)

![Screenshot_2024-03-06-13-26-45-872_com companyname timetable](https://github.com/radimitrov/CSharpShellApp/assets/51722783/1aba6aa1-c510-4f37-81da-ef90841f08de)

How can it be solved? Maybe it is a problem that it is inside a solution?@radimitrov

**Comment by radimitrov** [comment]
Yes, the IDE is only adding the top layer of references - the startup project. I will release a hotfix today. Both C# Shell and the APK plugin will need to be updated for it to work.

**Comment by radimitrov** [comment]
Should be fixed so I'm closing this. Haven't really tested with EF Core, however the IDE does now include references/packages from referenced projects so it should work.
