### ISSUE TITLE
Multiple parameters issue

### ISSUE THREAD

**Issue by Allison-E** [radimitrov/CSharpShellApp#37]
When a method has more than one parameter, all parameters that follow take the same data type as the first parameter and even takes the same value as the first.
```csharp
string word = GroupInWords(0, "46373");

public static string GroupInWords(int groupPosition, string numberGroup)
{
…
}
```
The values of `groupPosition` and `numberGroup` will be `46373`. And their data types will both be `int`.

**Comment by radimitrov** [comment]
No, it doesn't. C# is a strongly typed language
You are assigning the string "46373" to the string paramater numberGroup. It can't turn into an int automatically. 
Or you possibly have some error in your code that isn't visible in this stub.

**Comment by Allison-E** [comment]
For some reason, it worked in another project... I'll have to check my code well. Thank you
