### ISSUE TITLE
Sourcegenerator not working

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#375]
@radimitrov 
Before the update I was able to write working source generator,but now they don't work(requires partial class inside solution,I exported them as dll and referenced from the project where I wanted to use the source generator). Please help me!

**Comment by radimitrov** [comment]
@sedoLevi609 There hasn't been an update to the Roslyn compiler packages. There should be no reason source generators would stop working. Can you provide a test case?

**Comment by sedoLevi609** [comment]
@radimitrov  This is simple example: 
[SimpleExample.zip](https://github.com/radimitrov/CSharpShellApp/files/15153047/SimpleExample.zip)

**Comment by sedoLevi609** [comment]
Sorry,my mistake: I generated code with wrong type of string (used 3 " instead of 1)

**Comment by sedoLevi609** [comment]
@radimitrov I haver found how it is not working or because I didn't understand something,but please help me why this source generator not works(also contains a test for the source generator). Please help me. The files: 
[WrongExample.zip](https://github.com/radimitrov/CSharpShellApp/files/15155160/WrongExample.zip)

**Comment by radimitrov** [comment]
The quotes end up as just a syntax issue. This is caused by an update in March preventing source generators from being discovered. I'll see about fixing that soon.

**Comment by sedoLevi609** [comment]
@radimitrov I found a bug( I think so) with source generators: if I make an attribute with source generator the solution where I use it doesn't find the attribute after closing and reopening the project(or the app,inside solution). I can only solve this by creating a new solution or regenerate the generator dll and reference it again.

**Comment by sedoLevi609** [comment]
@radimitrov ifj you need an example:
[Example.zip](https://github.com/radimitrov/CSharpShellApp/files/15165375/Example.zip)

So reference generator as dll,then run Test project(it wil work),then exit app(or reopen solution) and run again Test project and it will say it doesn't find attribute(attribute needed to be added with source generator).

**Comment by radimitrov** [comment]
Looks like it all works now. I'm pushing it as another update today since it will be a while otherwise
