### ISSUE TITLE
Rx net

### ISSUE THREAD

**Issue by XaXa1234** [radimitrov/CSharpShellApp#376]
I am trying to use System.Reactive, and i got an exception every time  i run my code, 
`
System.TypeInitializationException: The type initializer for 'System.Reactive.Linq.Observable' threw an exception.
    at Observabletest.Program.DoObservable() in Program.cs:22 [22:13-29:18]
    at Observabletest.Program.Main() in Program.cs:15 [15`

whatever the version I am trying to use, trying to see the assembly i got a could not find Windows.Sdk.net v10.
Any ideas ?

**Comment by radimitrov** [comment]
Sorry for the late response. It was the app wrongly referencing the windows assemblies. It's be fixed for the next update soon
