### ISSUE TITLE
Console.ReadKey(true) glitch

### ISSUE THREAD

**Issue by kirk-evans** [radimitrov/CSharpShellApp#377]
Console.ReadKey(true) is supposed to suppress the echo of the pressed key, but based on what I'm seeing, it doesnt

**Comment by radimitrov** [comment]
This should be fixed when a new update comes out

**Comment by kirk-evans** [comment]
Not to sound "rushy' - but any idea when that might be?

( The rest of this belongs in a email, but I haven't found a way to send you one. )

I am really impressed with what you've done.  The amount of details you must have to deal with is staggering.
I don't know how much money you make off this, but I don't see how it could possibly make up for the number of hours you must be putting into it.   A Labor of Love, indeed.
So.. Many thanks for your hard work!
Kirk

**Comment by radimitrov** [comment]
I finished everything needed, including the other fixes. Last night I didn't have time but I just need to do some quick testing and it should be released tonight.
