### ISSUE TITLE
Console insert vs overwrite

### ISSUE THREAD

**Issue by kirk-evans** [radimitrov/CSharpShellApp#378]
If you set the cursor position before text that has already been written, and then write text, it inserts the text rather than overwriting the existing text.
I honestly don't know if that is the correct behavior or not.
Is the any way to control it?  In other words, set the "mode" of Console.Write(some text) to overwrite?

**Comment by radimitrov** [comment]
It shouldn't insert like that and it doesn't appear to happen now. Though it might have at some point. What version of the app are you using? Try updating.

**Comment by kirk-evans** [comment]
Works as expected.  Thank you!
