### ISSUE TITLE
C# on iPad?

### ISSUE THREAD

**Issue by kirk-evans** [radimitrov/CSharpShellApp#379]
I don't like my chances here, but is there any way I can run programs I've developed in c# she'll on an iPad?

**Comment by radimitrov** [comment]
As far as I know this is still the only app for C# if you're not looking for an online solution: https://continuous.codes/

**Comment by kirk-evans** [comment]
I'm not looking to develop on the iPad - I just want to run the programs I've written

**Comment by radimitrov** [comment]
Then no, there isn't a C#/.NET app that is only a runner and not an IDE for iOS. Same for Android.
