### ISSUE TITLE
Code Completion window size and Navigation

### ISSUE THREAD

**Issue by Code-With-NK** [radimitrov/CSharpShellApp#387]
Just as you provide an option in settings to change the scale of the code completion window height, it would be great if we could also adjust its width to prevent long names from being cut off (see the picture below).

Additionally, when the code completion window is visible, I cannot navigate through the list(By pressing up-down keys). Instead, the cursor moves up or down while keeping the completion window visible. Please address this issue as well.

![IMG_20240704_204105](https://github.com/radimitrov/CSharpShellApp/assets/118751244/f0c18034-ea07-4ea9-8ceb-4a731c6d53f4)

**Comment by radimitrov** [comment]
Yes, the keyboard issue will be fixed.
I will try to make the completion window scale horizontally first

**Comment by Code-With-NK** [comment]
@radimitrov Thank you!

**Comment by radimitrov** [comment]
There should be an update by tomorrow. The width should now auto scale up to 80% screen width. However I don't like how the keyboard navigation turned out so I will be fixing that later.

**Comment by Code-With-NK** [comment]
@radimitrov I just checked, and the update has been released with both features added. Thanks for the quick update!
