### ISSUE TITLE
Code completion goes off

### ISSUE THREAD

**Issue by Allison-E** [radimitrov/CSharpShellApp#39]
The app seems to refresh and code completion and real time code error checking suddenly stops.

**Comment by radimitrov** [comment]
The only way I can think of that can happen is in ad supported mode.
It checks for Internet connectivity and if anything was loaded within the last 15 minutes as a basic adblock measure.
If this isn't the scenario then it might "fix itself" soon since the next update is quite extensive internally.

**Comment by Allison-E** [comment]
Okay, I am using the ad supported mode currently so I guess you're right. Thanks
