### ISSUE TITLE
URL BASED SHELL NAVIGATION 

### ISSUE THREAD

**Issue by CliffChoongo** [radimitrov/CSharpShellApp#393]
Everytime I register a page and try to navigate to the page using the shell an exception is throwing that a duplicated route has been found.I don't if you can help me with this, I would be greatful for that.

**Comment by radimitrov** [comment]
Navigation seems to work. However I assume you are manually registering pages via code? In that case I'm not sure what could be wrong without seeing the relevant code.

**Comment by radimitrov** [comment]
This should be fixed in v3.3.32

**Comment by CliffChoongo** [comment]
Thanks.
