### ISSUE TITLE
It does not allow me to use the Android.Gms.Ads package

### ISSUE THREAD

**Issue by CaflosGTI001** [radimitrov/CSharpShellApp#40]
Everything works correctly until I try to add a Xamarin.GooglePlayServises.Ads NuGet package to a Xamarin Forms project which will allow me to use the namespace Android.Gms.Ads but They do not appear to me, like some libraries to add AdMob ads to it. 
Also when I try to use another library this error happens to me, when using AdMob.
![Screenshot_2020-04-29-22-49-17](https://user-images.githubusercontent.com/64661559/80835957-cea39f00-8bc1-11ea-8c82-1a0e477939a2.png)

**Comment by radimitrov** [comment]
Click "browse loaded assemblies" in the project drawer and add it from the internals there.
 However APK exporting won't work in this case due to the reasons explained in the NuGet package downloader

**Comment by radimitrov** [comment]
Also ads won't work at all. I'm almost certain they would only be able to use the C# Shell ID

**Comment by CaflosGTI001** [comment]
oh it's okay.

**Comment by CaflosGTI001** [comment]
En
