### ISSUE TITLE
GUI Suggestion 

### ISSUE THREAD

**Issue by Tomomoto10** [radimitrov/CSharpShellApp#403]
Are you able to change the sidebar so that once you have purchased the premium, the premium menu disapears? Ive clicked into it multiple times thinking my purchse had disapeared because premium is the first item in the menu like an Ad, which for free use is perfectly fine.

**Comment by radimitrov** [comment]
That shoudn't be really necessary since it  It might even violate Google rules to remove it but I don't want to dig throught them right now to confirm. Best I can try is making it grayer
