### ISSUE TITLE
Missing types in System.Security.Cryptography 

### ISSUE THREAD

**Issue by FlashyDJ** [radimitrov/CSharpShellApp#405]
Loads of types are missing in `System.Security.Cryptography`. Code that works in the previous version now throw errors when compiling.

Types like `RandomNumberGenerator`, `CryptographicOperations` is mssing.

Viewing the type list only show two entries.
![Type List](https://github.com/user-attachments/assets/6c69592f-9690-4f54-abe7-25d7551be740)

**Comment by radimitrov** [comment]
Should be fixed now

**Comment by FlashyDJ** [comment]
🍻 Cheers, it works now.
