### ISSUE TITLE
Theme problems

### ISSUE THREAD

**Issue by giladfrid009** [radimitrov/CSharpShellApp#43]
The recent update reset my editor theme which is unfortunate.
Also, the custom class coloring doesn't seem to work. (at least with the visual studio dark theme)

Btw, thanks for adding a preview for the themes.

**Comment by radimitrov** [comment]
The class colouring should be fixed and kick in within a few seconds in the update I uploaded a few hours ago

**Comment by radimitrov** [comment]
The missing theme must be "obsidian_lite". I can add it again. It is technically one I added manually so it must have been deleted during the Ace Editor upgrade.
