### ISSUE TITLE
Themes feature suggestions

### ISSUE THREAD

**Issue by giladfrid009** [radimitrov/CSharpShellApp#44]
In my opinion, the big amount of editor themes is a bit confusing and hard to find the desired theme.

Therefore, i suggest keeping several mainstream themes and adding an option to create a custom theme for those who want something specific

**Comment by radimitrov** [comment]
Custom themes can't be created dynamically for this editor. That is why I added the 300 themes and a search bar. They were originally 600

**Comment by radimitrov** [comment]
Actually themes can't be created dynamically, but the same method used for the custom type color can be applied to seemingly acheive that. So basically 1 new theme that will be modifiable during runtime.
It should also be able to "inherit" from any of the other themes which would mean they can be used like a creative reference.

**Comment by CaflosGTI001** [comment]
is it possible for you to make a guide to use these themes?

**Comment by radimitrov** [comment]
> is it possible for you to make a guide to use these themes?

For the theme customization I'm adding soon? I don't think there is a need for that.
Editing a theme will be started just by a single click followed by picking colors with realtime preview.
