### ISSUE TITLE
Highlights Suggestion

### ISSUE THREAD

**Issue by DrakeUser123** [radimitrov/CSharpShellApp#46]
##I have a suggestion, its a small feature, but it can really helps, it is where you highlight a text, codes stuff so that it will remind you that you have something very important to change in codes. 
It is Sorta like when you select: (words, num ,etc.), you have this "blue box" selected thing which will be gone when unselected. That blue box is what i want to ask for suggestion but not the part where it automatically deselect only when it stays there, its like this Hello but in a blue box. Also the box has a costomizable color :D dont know if this feature is already in the app, its up to you to decide whether add it or not.

**Comment by radimitrov** [comment]
Can't. Such extensive dynamic markings would probably kill performance in this editor and likely be confusing.
Besides this can done with a "TODO" comment for the block, which can be more descriptive.
