### ISSUE TITLE
Adding assembly reference 'OpenTK'

### ISSUE THREAD

**Issue by mavyfaby** [radimitrov/CSharpShellApp#48]
I'm trying "CocosSharp for Xamarin.Forms" and this error occured, see below:

![Screenshot_2020-06-06-14-53-25](https://user-images.githubusercontent.com/51808724/83938295-8ea98a80-a805-11ea-9c8b-91d23f6ddbf6.png)

It says, I will add a reference to assembly "OpenTK" but how?

**Comment by radimitrov** [comment]
As far as I remember I had to remove OpenTK to keep the APK < 100 MB last year. AAB is now supported and in use so I can readd it. Not sure if that will enable CocosSharp, though.

**Comment by mavyfaby** [comment]
So, this mean that CocosSharp won't work?

**Comment by radimitrov** [comment]
Probably won't work, depends on how it works internally.

**Comment by mavyfaby** [comment]
Okay, I'll close this issue.
