### ISSUE TITLE
Supported Game Engine with Xamarin.Forms

### ISSUE THREAD

**Issue by mavyfaby** [radimitrov/CSharpShellApp#49]
Certainly this is not an issue, but I want to try creating games. I've searched some like MonoGame and UrhoSharp but I don't know how to use them. The docs are not well explained. Can someone list some supported Game Engines? Thank you.

**Comment by radimitrov** [comment]
That would need at least support for compiling Java in addition to the tools to basically compile an entire Xamarin.Android application. Visual Studio has that, but it isn't exactly cross-platform.
So there probably can't be support for most game engines like CocosSharp and MonoGame.
However a Javascript/HTML5 game engine with C# bindings should work. I'll look into that.

**Comment by mavyfaby** [comment]
Ohh I see but using the webview, still the performance is the same as the native game?

**Comment by radimitrov** [comment]
Well, no. But todays browsers and phones are quite efficient. So maybe 80% performance.

**Comment by mavyfaby** [comment]
Okay thanks😊
