### ISSUE TITLE
Can you add this?

### ISSUE THREAD

**Issue by DrakeUser123** [radimitrov/CSharpShellApp#51]
I have a suggestion can you add this? :D
class Program
	{
	|	static void Main(string[] args)
	|	{
	|	|	Console.WriteLine("Hello World!");
	|	}
	}
This line lines like in visual studio or code, where you know where what content does ex. static void Main{ } contains.... It may be usefull if you dont know whats going on. 
Atleast make it as an option.

**Comment by radimitrov** [comment]
Indent guidelines? Done.
They used to be on by default. No idea why they were was off now.
