### ISSUE TITLE
A little margin for the console

### ISSUE THREAD

**Issue by DrakeUser123** [radimitrov/CSharpShellApp#52]
![Screenshot_2020-06-19-15-06-03-70](https://user-images.githubusercontent.com/65073109/85106477-d5a07280-b23e-11ea-8d5d-d49dfa0bdf02.png)
This is a very little issue, it is not even a bug maybe:
When i do landscape on my device(currently my phone) I see this part wherein some part of it can't be seen unless you add a space at your code:
Console.WriteLine(" Hello World"); I add alittle space for it so it can be seen,
Console.WriteLine("Hello World"); this is before...

Output without space:
ello World

Output with space:
Hello World

Note: This only affect landscape mode, and not portrait, and also I' am not sure if this only affects my device and not other devices like tablets, Other device models etc... Or is it only my device that do this stuff when on landscape. It is not pretty much to bother anyways, if you can fix this or add aliitle margin or a tiny one at the front, it can be fix... Also if not fix, it's ok Im really used to spacing at coding output.

Edit: i tested this on my other device and its normal,  it is my phone screen display is the problem.... Pls add an option for tiny margin at console welp its up to you to decide whether add it or not and also "Thanks for the Response"  You are a really great developer :D

**Comment by radimitrov** [comment]
That problem doesn't seem possible. It can't basically render out of bounds. Also there already is a tiny possitive left margin, though I don't see it here for some reason. It was added a year ago because my screen protector has black bands on the side so it must be placed with micron pricision to not cover any of the screen. Figured I wasn't the one.  Maybe that is the issue here?

Is this image intended to be indicative of the issue? Is it "Hello Shape World" or " Hello Shape World", because all of it can be seen. Looks like including the ReadLine cursor, which is basically on an empty line.

**Comment by DrakeUser123** [comment]
The first part you've said is the issue here, I thought I'm the only one having this problem, and the part you've said a screen protector with black bonds on the side, I did'nt notice that, i currently seeing black bounds on the side of my phone....
Also I've discovered (Its pretty wierd actually):

When my code is only:
Console.WriteLine("Hello World!");
Then I print it out, there is already a tiny margin which is What i wanted.

And then when I add:
Console.WriteLine("Hello World!");
Console.ReadLine(); 
The little Margin was gone, only showing Half of the H in Hello World!.

And then i also removed the Console.ReadLine();
To see if i can get the tiny margin again...

But the output remains the same as the part where i added
Console.ReadLine(); meaning the tiny margin is alread gone only showing
Half of "H"ello World!

I'm confuse, :{ maybe its a bug?

**Comment by radimitrov** [comment]
Now makes sence, when the keyboard opens. I think I fixed that too. The update went live 15 minutes ago.  Update and try again

**Comment by DrakeUser123** [comment]
Oh You've Updated it, thats neat :) ! Welp that was fast...

**Comment by radimitrov** [comment]
Yeah, your timing conceided 5 minutes of me releasing an updating that fixes something else, so it just took another 3 minutes :D

**Comment by DrakeUser123** [comment]
It took me awhile to update it, But the issue is resolved now, Thanks!

**Comment by radimitrov** [comment]
Welcome. I'm closing the issue, then.
