### ISSUE TITLE
"One dark Pro Theme" Suggestion 0_o

### ISSUE THREAD

**Issue by DrakeUser123** [radimitrov/CSharpShellApp#53]
I see this in vscode alot, they say it's popular so I may want to try this theme. Can you add this theme suggestion?

**Comment by radimitrov** [comment]
Probably. Is [this](https://tmtheme-editor.herokuapp.com/#!/editor/theme/One%20Dark) the same theme? Looks like it.

**Comment by DrakeUser123** [comment]
Probably not, i think its like monokai with some font-family in it.

**Comment by radimitrov** [comment]
I see, then it isn't really supported. Any kind of non-monospaced font will break the entire editor.
Though you can create an approximation with the app's theme editor, if you want.

**Comment by DrakeUser123** [comment]
Ok, but ill take the one you mentioned, its better than nothing.

**Comment by radimitrov** [comment]
Yeah, it is a nice enough theme. I'll see if it converts ok.

**Comment by radimitrov** [comment]
Apparently there is no need to add it since It is already included and named "one_half_dark"
