### ISSUE TITLE
Bug when opening a file in a project

### ISSUE THREAD

**Issue by anonymuspro** [radimitrov/CSharpShellApp#55]
I had a file Downloader.cs, I save it and open the second file MainPage.cs as a result, all the code from the first file is in the second and so on with all the files

**Comment by radimitrov** [comment]
Ok, so this is only with a Xamarin.Forms project? That narrows down the problem a lot.
Is Downloader.cs the Main project/source file?

**Comment by bishow101** [comment]
It occurs after running approx 5-8 times. Although it doesn't have fixed interval. Try to create a xarmain app by yourself and figure out the problem.

**Comment by sashamsuper** [comment]
Similar problem. Occurs when using Csharp_shell.OpenFileDialog. Project in attachments.(If you compile from the someFile window, the ReSave file will be overwritten by the someFile file) Duplicated to mail.[project example](https://github.com/sashamsuper/ReSaveFile)

**Comment by anonymuspro** [comment]
It also happens when you delete a file from a project, it is deleted but remains open in the editor, and then when you open other files, the code is copied to all files

**Comment by radimitrov** [comment]
@anonymuspro @sashamsuper Yes, I can confirm both these problems and they are easily fixable.

**Comment by radimitrov** [comment]
@anonymuspro However the original problem with the Xamarin.Forms Downloader.cs, and  MainPage.cs example remains elusive after about 30 tries each on 2 devices. I have added some additional safeguards to try and prevent this. I'll probably update in < 2 days, tell me if it works properly after that.

**Comment by radimitrov** [comment]
Ok, I think everything is fixed now.
I just uploaded the update. Version 2.0.7.7 should be live within 12 hours.
