### ISSUE TITLE
Extensions  does not work

### ISSUE THREAD

**Issue by anonymuspro** [radimitrov/CSharpShellApp#56]
I tried to make extensions  But your compiler shows an error. My code:

`
public static VideoQuality QualityFromString(this VideoQuality, string text)
        {
            switch (text)
            {
                case "144":
                    return VideoQuality.Low144;
                case "240":
                    return VideoQuality.Low240;
                case "360":
                    return VideoQuality.Medium360;
                case "480":
                    return VideoQuality.Medium480;
                case "720":
                    return VideoQuality.High720;
                case "1080":
                    return VideoQuality.High1080;
                default:
                    return VideoQuality.Medium360;
            }

            return VideoQuality.Medium360;
        }`

**Comment by radimitrov** [comment]
What is the error?

**Comment by anonymuspro** [comment]
It turns out that this method should be an extension for the VideoQuality class, but when accessing this method through the class, it shows an error that the method was not detected

**Comment by radimitrov** [comment]
I don't know from where the VideoQuality is so I can only guess and without seeing any errors. Post the error(s) here. 
You are creating a VideoQuality object, correct? Is the Extension class static?

**Comment by anonymuspro** [comment]
VideoQuality and Extensions it a static class

**Comment by radimitrov** [comment]
I ask again - what is the compilation error? What error does the compiler show? How are you trying to use the code?
This is obvously some kind of syntax or logic error somewhere in your code. 
However I can't help beyond giving you a basic example since you aren't sharing the error itself.

Example of extension method:
```
public class Ext
{
   public static string someExtension(this string str, int n)
   {
        return str + n;
   }
}



//Usage
var str = "text";
Console.WriteLine(str.someExtension(4));

**Comment by radimitrov** [comment]
Oh wait. VideoQuality is a static class? 
No, C# doesn't support extension methods for static classes. You need an instance like I asked up there.
That is why the syntax is "void ExtensionMethod(**this** obj)"
