### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by anonymuspro** [radimitrov/CSharpShellApp#57]
I need  use class Context in my programs
Xamarin.Forms;
At compilation of the program these errors get out:

The type 'Context' is defined in an assembly that is not referenced. You must add a reference to assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

 (56, 17):  The type 'Context' is defined in an assembly that is not referenced. You must add a reference to assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

In code, I call - Xamarin.Forms.Forms.Context

**Comment by radimitrov** [comment]
Reference the assembly from the "assembly references" button in the project tab
