### ISSUE TITLE
Application crashes when breaking a while loop

### ISSUE THREAD

**Issue by CursedSheep** [radimitrov/CSharpShellApp#6]
Hello, to reproduce my problem simply create a while loop like this.
while(true) 
{
string a = Console.ReadLine() ;
if(a.Length == 0) break;
else Console.WriteLine("ok");
}

**Comment by radimitrov** [comment]
It works.This isn't what's causing a crash

**Comment by CursedSheep** [comment]
really? how could i determine the problem? When running the application, it crashes for me when input is none.

**Comment by radimitrov** [comment]
The while loop itself isn't causing the issue. It was impossible for it to be the problem but I tested it anyway. 
That code snippet is all the information I have at the moment. Without knowing the actual full context or code it is impossible to asnwer what the problem is

**Comment by CursedSheep** [comment]
is there a way for you to trace the bug? what add a feature about logging events before crash happens?

**Comment by radimitrov** [comment]
Closest viable thing to that is a managed (C#) stacktrace of the Exception that caused the crash.
That already exists and they are saved in the internal storage under "CSharpShell/crashlogs". Look in that folder. 

The app should also automatically  restart and show the crash stacktrace. 
And since about 2 months ago there is a "send report" button too.
I'm guessing you're using a much older version and need to update the app for that.

**Comment by CursedSheep** [comment]
the crashlogs folder is empty, i am also using the latest version.

**Comment by CursedSheep** [comment]
here's what happens, as soon as i enter my empty input, application just goes still. You can describe it like it is in an infinite loop of doing nothing. then when i tap on the x button to stop the execution, the application restarts.

**Comment by radimitrov** [comment]
Well, I just did that. With the exact code snipped up there.
It doesn't freeze. It exited the loop and continued to the and of the program successfully.
You're probably doing something more in your code. Does it have something to do with threading?

**Comment by CursedSheep** [comment]
ok here's the code.
`         List<string> input = new List<string>();
         while(true)
         {
             Console.Write("input: ");
             string a = Console.ReadLine();
             if(a.Length == 0) break;
             else input.Add(a);
         }
         foreach(string o in input)
         {
             int temp = 1;
             string[] split = o.Split(' ');
             int.TryParse(split[0], out int f);
             int.TryParse(split[1], out int s);
             if(f <= s)
             {
                 for(int i = f; i <= s; i++)
                 {
                     if(i%2==0)
                     {
                         temp *= i;
                     }
                 }
                 Console.WriteLine(temp);
             }
             else Console.WriteLine("not applicable");
         }`

**Comment by radimitrov** [comment]
It seems to work fine as you can see in the attached video. 
This might be an OS version issue. Or an issue specific to only a few devices. Possibly in the Mono runtime.
But lets assume it isn't that for now.

CSharpShell's OpenFileDialog is basically the same as Console.ReadLine under the hood.
They use a ManualResetEvent to signal completion which is done by raising a "OnResult" event. It is possible the event handler might somehow get unhooked essentially resulting in an infinite waiting loop. If that is the case it can be fixed easily when I remove the need for "OnResult".
Try running this several times:
```
OpenFileDialog.Title = "Pick some file";
if (OpenFileDialog.Show() == DialogResult.OK) Console.WriteLine(OpenFileDialog.File);
Console.WriteLine("If we're here then it works properly");
```


[code_vid.zip](https://github.com/radimitrov/CSharpShellApp/files/3825383/code_vid.zip)

**Comment by radimitrov** [comment]
Okay, I removed the legacy code and the update should be live soon. Hopefully that fixes this rare and so far unreplicatable issue.

**Comment by CursedSheep** [comment]
ok, i just recorded a video that just shows how it crashes. Gonna upload it once i get home.

**Comment by CursedSheep** [comment]
[Untitled.zip](https://github.com/radimitrov/CSharpShellApp/files/3828239/Untitled.zip)
here's the video.
but it's still not working on latest version.

**Comment by radimitrov** [comment]
Notice how the last line dissapears?
I think something is going wrong with the indexing or selection operations. Must be an obscure keyboard or device "enter" input problem.
No problem, I'll catch the key event directly, silence it and proceed to do the operations .

**Comment by CursedSheep** [comment]
thanks. hope you can fix it!

**Comment by andrejka955** [comment]
CursedSheep I need help

**Comment by radimitrov** [comment]
If it isn't related to this presumably solved issue, then open another one.

**Comment by CursedSheep** [comment]
> > CursedSheep I need help
> 
> If it isn't related to this presumably solved issue, then open another one.

I just tried it. And it just catches the error. It doesn't crash but the application doesn't continue either.

**Comment by andrejka955** [comment]
> > > CursedSheep I need help
> > 
> > 
> > If it isn't related to this presumably solved issue, then open another one.
> 
> I just tried it. And it just catches the error. It doesn't crash but the application doesn't continue either.

I'm late side did u actually scam or what we were all scared u died af the hell? Add lateside#1337

**Comment by andrejka955** [comment]
Add me on discord..  Bruh we were about to do ceremony

**Comment by andrejka955** [comment]
Your discord acc suspended add back

**Comment by CursedSheep** [comment]
Actually you can't chat here, I can't make discord right now and not home. I can't tell you where I am right now but it's something serious.

**Comment by andrejka955** [comment]
Ok ok we believe you we thought u're in hospital / died / on then run / smth bad happened I guess we were right

**Comment by andrejka955** [comment]
Why didn't you tell us anything btw this is weird

**Comment by andrejka955** [comment]
You act like if you killed someone wtf stop just sah

**Comment by satam1337** [comment]
yo cursed we know you work for discord hook us up with that free nitro

**Comment by satam1337** [comment]
pls

**Comment by satam1337** [comment]
cursed

**Comment by satam1337** [comment]
Cursed is there any way to talk to you? Please.
