### ISSUE TITLE
Xamarin buttons not working with the script

### ISSUE THREAD

**Issue by s4rkrda** [radimitrov/CSharpShellApp#65]
so i wrote a basic xamarin script, a button when you press it it shows a massage and i wrote the code on my c# script but no matter how much i press it it doesn't work at all
I don't know what is the problem and i'm not getting any errors

**Comment by radimitrov** [comment]
Xamarin.Forms I guess? Without seeing any code the only thing I can say is are you sure you have hooked up the click event?

**Comment by s4rkrda** [comment]
Yes i used the clicked event and wrote the to do code in my c# but it doesn't work
This is what i done

<Button Text="Say Hello" Clicked="Button_Clicked"></Button>

void Button_Clicked(object sender, EventArgs e){
    DisplayAlert("Title", "Hello", "ok");
}

And the files are connected too!
Thanks.

**Comment by radimitrov** [comment]
This code works on my end - no error. Are you using the XAML page preview mode?

**Comment by s4rkrda** [comment]
Yep i'm using the XAML preview mode, i don't get any errors but the button still doesn't work

I don't know what to do and i'm just a bigginner.

**Comment by radimitrov** [comment]
Indeed, that's it. Preview mode just quickly loads and shows the XAML without any attached C# code, hence there are no events.
I'll add that to the toast message.
