### ISSUE TITLE
Able to open main file 2 times in the same proj

### ISSUE THREAD

**Issue by giladfrid009** [radimitrov/CSharpShellApp#7]
I was able to open the main file a second time, after creating another file and then selecting main and the new file as the files to open.
That causes the program to be unrunnable, since the compiler now thinks it has 2 main files, eventhough it's the same file.

I couldn't figure out how to remove the second main file from the project.

**Comment by radimitrov** [comment]
I'll add a safeguard to prevent this.
For now open "your_proj.cspro" in a text editor and delete "//+src=your_proj.cs"
