### ISSUE TITLE
Packages issues

### ISSUE THREAD

**Issue by velfolds** [radimitrov/CSharpShellApp#73]
I have updated the app to the latest version and when am creating xamarin forms app every time I hit the launch button I'm constantly getting errors like the sample below and it has to do with the referenced libraries. 

(10, 1):  Metadata file 'assemblies/System.dll' could not be opened -- PE image doesn't contain managed metadata.

  (-10, 1):  Metadata file 'assemblies/System.Data.dll' could not be opened -- PE image doesn't contain managed metadata.

**Comment by radimitrov** [comment]
Did it happen in a previous app version? I think the are 2 possibilities.
1. Your device doesn't have enough RAM to decompress the internal assemblies. Unlikely as there would be more errors.
2. The app is loading the package dependencies as it should but one of them haves an included native dll - for example the System.dll from .NET Framework 4.8. Something like that is more likely. What are your packages?

**Comment by velfolds** [comment]
Thank you for your quick response I believe one of the packages I have downloaded has a native dll because my RAM size is 2GB and after clearing out all packages from the global packages folder all seems to be ok
