### ISSUE TITLE
additional source files autocompletion bug

### ISSUE THREAD

**Issue by ModMapper** [radimitrov/CSharpShellApp#74]
When enabling the "Enable project autocomplete from additional source files" setting

Autocompletion of fields and properties is not working.

I think autocompletion read code twice...

**Comment by radimitrov** [comment]
Just properties? Doesn't sound like a bug. You're probably leaving them private.

**Comment by ModMapper** [comment]
> Just properties and fields? Doesn't sound like a bug. You're probably leaving them private.

For example, if you enable the setting, the code in the file "xxx.cs" cannot automatically complete fields and properties within "xxx.cs".

**Comment by radimitrov** [comment]
Well, it appears to work with the option enabled. So the problem must be in your code logic.
Is "Class2" static? Make sure the members are public and static.
Or is "Class2" not static? Make sure you're creating an instance of "Class2" and that the members are public and not static.

**Comment by ModMapper** [comment]
> Well, it appears to work with the option enabled. So the problem must be in your code logic.
> Is "Class2" static? Make sure the members are public and static.
> Or is "Class2" not static? Make sure you're creating an instance of "Class2" and that the members are public and not static.

This has nothing to do with the code in other files.

additional source files autocompletion off
![20201223_142622](https://user-images.githubusercontent.com/18527479/102963080-9b849600-452b-11eb-8880-fd2220014280.jpg)
Autocompletion is normal

additional source files autocompletion on
![20201223_142559](https://user-images.githubusercontent.com/18527479/102963184-d4246f80-452b-11eb-8a9f-e6e791921d78.jpg)
Autocompletion not shown

Additional test results. This problem appears to occur after compilation once except for the main file.

**Comment by radimitrov** [comment]
Thanks. It's fixed now.
