### ISSUE TITLE
Assembly Compiling Issues

### ISSUE THREAD

**Issue by velfolds** [radimitrov/CSharpShellApp#75]
I have dumped all my nuget packages and am using the app's referenced Assemblies but am still getting the same errors

(-10, 1):  Metadata file 'assemblies/System.Core.dll' could not be opened -- PE image doesn't contain managed metadata.

  (-10, 1):  Metadata file 'assemblies/System.Xml.dll' could not be opened -- PE image doesn't contain managed metadata.

Like I mentioned earlier my RAM is 2gb  android 8.0 and the xamarin forms previewer is working fine but when 
compiling I get the above errors & there is also this:

System.InvalidOperationException: SetFlags must be called before Init
  at Xamarin.Forms.Forms.SetFlags (System.String[] flags) [0x0000f] in <4df20df9ee5a43729dd8ba50f24273d3>:0 
  at CSharp_Shell.Activities.XamarinFormsActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0003c] in <232c825eadc94f59b6e040d7c6ebcace>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <a54fd02a94254b8f91efc9ea3cec736c>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)

and yet am not using any experimental feature in my xaml or code behind

**Comment by radimitrov** [comment]
The "PE image doesn't contain managed metadata" is strange. But at this point unlikely to be a memory issue.
The next update should fix the flags part at least.

**Comment by Blackwood416** [comment]
(-10, 1):  Metadata file 'assemblies/System.dll' could not be opened -- PE image doesn't contain managed metadata.

  (-10, 1):  Metadata file 'assemblies/System.Xml.dll' could not be opened -- PE image doesn't contain managed metadata.


I got the same problem while I am running a Xamarin sample project which from the Xamarin | Microsoft Docs.

**Comment by cometears** [comment]
it takes too long to compile to the point that I'm waiting for nothing at all

**Comment by radimitrov** [comment]
> (-10, 1): Metadata file 'assemblies/System.dll' could not be opened -- PE image doesn't contain managed metadata.
> 
> (-10, 1): Metadata file 'assemblies/System.Xml.dll' could not be opened -- PE image doesn't contain managed metadata.
> 
> I got the same problem while I am running a Xamarin sample project which from the Xamarin | Microsoft Docs.

With the latest version of the app? Which sample? Doesn't seem to happen with the Bug Sweeper example.
I think assembly deceompression might be failing on some devices at initial load. How much RAM does yours have?

**Comment by radimitrov** [comment]
> it takes too long to compile to the point that I'm waiting for nothing at all

Define long. It is to be expected for a low end device. For example 1GB, 4x1GHZ would be around 30 seconds for initial JIT and under 3 seconds for each compilation after that.
Though most of todays devices would yeild a JIT of <= 10s and 1-2s after that.

**Comment by Blackwood416** [comment]
> > (-10, 1): Metadata file 'assemblies/System.dll' could not be opened -- PE image doesn't contain managed metadata.
> > 
> > (-10, 1): Metadata file 'assemblies/System.Xml.dll' could not be opened -- PE image doesn't contain managed metadata.
> > 
> > I got the same problem while I am running a Xamarin sample project which from the Xamarin | Microsoft Docs.
> 
> With the latest version of the app? Which sample? Doesn't seem to happen with the Bug Sweeper example.
> I think assembly deceompression might be failing on some devices at initial load. How much RAM does yours have?
> 
> 

I have a xiaomi MI6 with 6GB RAM and a old Android device with 3GB RAM,but I got the same error on both of my devices.I am using the latest version of the CsharpShell app.And I run this sample https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/database?pivots=windows

I just follow the tutorial,copy the code,make some necessary changes(or some header files will cause errors),add the nuget package to the project.But run the program directly or export program as APK got the same error.

**Comment by radimitrov** [comment]
@Blackwood416 Yes, that was the new version 2.0.14.5. The next one still has a chance of fixing this. 
I downloaded and imported the sample project and it works in 2.0.14.5. Try the attached project. 

[Notes.zip](https://github.com/radimitrov/CSharpShellApp/files/5771130/Notes.zip)

![Screenshot_2021-01-05-17-28-15-764_com radinc csharpshell](https://user-images.githubusercontent.com/56889141/103665524-2e85ed00-4f7c-11eb-8a62-2f3314992f66.jpg)

**Comment by Blackwood416** [comment]
@radimitrov ![IMG_20210106_170909.jpg](https://user-images.githubusercontent.com/73172752/103750681-19739180-5042-11eb-88c4-c6945b0470d6.jpg)

**Comment by radimitrov** [comment]
Thanks everyone for finding the issue! 
Now that I've actually slept it will also automatically clear bad assembly loads in the next update. 
So there probably won't be a need to recompile in most cases.
