### ISSUE TITLE
Metadata file 'assemblies/System.Xml.dll' could not be opened

### ISSUE THREAD

**Issue by kmatthieu15** [radimitrov/CSharpShellApp#76]
Sometimes I get this error in compilation `(-10, 1):  Metadata file 'assemblies/System.Xml.dll' could not be opened -- PE image doesn't contain managed metadata`. I dont even know how to get rid of it. It needs a fix. Its annoying me.

**Comment by radimitrov** [comment]
I guess this is identical to issue #75 ? Well, it is if a restart sometimes fixes it.
Hopefully purging the failed assembly decompression/loading attempt after it happens is enough for a quick fix. I'm uploading it now.
