### ISSUE TITLE
System.String

### ISSUE THREAD

**Issue by typhonn353** [radimitrov/CSharpShellApp#8]
How can I add the System.String Class? Your nuget app doesn't find it and it is not listed in the dll's.

**Comment by radimitrov** [comment]
There is no such thing as a Nuget package for that class.
System.String is a built in class in the .NET/Mono framework since version 1.

**Comment by typhonn353** [comment]
So I can't add it?

**Comment by radimitrov** [comment]
No, because it is already included. A built-in type into the runtime.  If you're using C# you already have the "System.String" and the "string" alias.
