### ISSUE TITLE
Experimental features

### ISSUE THREAD

**Issue by Ahmedmarzouk0000** [radimitrov/CSharpShellApp#85]
How to use experimental features like the SwipeView ?

**Comment by velfolds** [comment]
Swipe view won't work but there are other features that work if you add the experimental flags

**Comment by radimitrov** [comment]
The "SwipeView_Experimental" flag should be enough. What is the error it shows?

**Comment by Ahmedmarzouk0000** [comment]
Hi there! Thanks for replying to this.
When I call Xamarin.Forms.Forms.SetFlags("SwipeView_Experimental");
It produces this error:
![Screenshot_20210204-232052.jpg](https://user-images.githubusercontent.com/64537215/106956929-fe2e9b80-673f-11eb-93e1-b9956506f69f.jpg)
Where is the Xamarin.Forms.Forms.Init(); called?

**Comment by radimitrov** [comment]
Before "Ui.RunOnUiThread". Try it like this and it should work.
![Screenshot_2021-02-05-09-01-46-364_com radinc csharpshell](https://user-images.githubusercontent.com/56889141/107001640-a705e680-6792-11eb-938b-b4d1e134f46c.jpg)

**Comment by Ahmedmarzouk0000** [comment]
It works! Thanks for your time!
