### ISSUE TITLE
Couldn't load assembly 

### ISSUE THREAD

**Issue by thong927** [radimitrov/CSharpShellApp#88]
![Screenshot_20210321-192641](https://user-images.githubusercontent.com/81086739/111904967-f4f15800-8a7b-11eb-9310-0236883aa950.jpg)
<B><p1>Couldn't load assembly </p1></B><br>
<p2>This error occurs frequently on <a href= "https://www.google.com/amp/s/m.gsmarena.com/samsung_galaxy_j2_pro_(2018)-ampp-8904.php"><I><B>my device</B></I></a>.  It does not load system assemblies, packages and even from the path. </p2>

**Comment by radimitrov** [comment]
It shouldn't occur more than once after the app has been launched? It's mainly a RAM issue - not enough freed up to decompress all assemblies sequentially. Next update should reduce ram usage considerably. So it will be less frequent, at least.
