### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by thong927** [radimitrov/CSharpShellApp#89]
<B>Bug! </B><br>
<p>I get annoyed by the error of overwriting my code save file.  It has been corrupted from the old version until now, but when I was writing the code a rectangular box appeared and all my code files were overwritten, it took the code I was writing and overwrote all of it.  So many duplicate code error messages appear.</p><br>
<B>Please fix it!</B>

**Comment by radimitrov** [comment]
That is the current problematic project system - no fixing if it keeps happening after all this time.
I'm in the process of implementing a new project system. So that issue will disappear with the old one.

**Comment by alvgtrujillo** [comment]
> Bug!
> 
> I get annoyed by the error of overwriting my code save file. It has been corrupted from the old version until now, but when I was writing the code a rectangular box appeared and all my code files were overwritten, it took the code I was writing and overwrote all of it. So many duplicate code error messages appear.
> 
> 
> Please fix it!

Same error 17/02/2021
